### ISSUE TITLE
vue3+ts报错

### ISSUE THREAD

**Issue by endlessly** [501351981/vue-office#10]
vue-office_docx:

main.ts:27 Uncaught (in promise) Error: Dynamic require of "vue-demi" is not supported
    at chunk-QJ3XAL7T.js?v=262d692d:12:9
    at @vue-office_docx.js?v=115aedc0:16:88
    at node_modules/@vue-office/docx/lib/index.js (@vue-office_docx.js?v=115aedc0:17:7)
    at __require2 (chunk-QJ3XAL7T.js?v=262d692d:18:50)
    at @vue-office_docx.js?v=115aedc0:5320:31

**Comment by 501351981** [comment]
是不是vite版本比较老，我用vite创建了ts的Vue3项目没有看到报错，我的vite版本： "vite": "^4.1.0", 如果方便可以把项目代码发我微信，我自己试试 \_hit757_

**Comment by endlessly** [comment]
嗯，我的vite版本是2.3，升级到4.1之后就没有报错了
