### ISSUE TITLE
图片 图标 闪烁

### ISSUE THREAD

**Issue by hbsjmsjwj** [501351981/vue-office#100]
excel里面有图片，图表，然后点击了页面然后图片图表就会不见。然后滚轮动一下 就显示了，、
你的在线示例也会有这个现象

**Comment by bistuly** [comment]
调试了一下.①mousedown时触发了Spreadsheet.sheet.editor.clear事件，vue-excel中修改了Spreadsheet.sheet.editor.clear事件， 在clear事件时采用setTimeout重绘图片。那么问题就来了，setTimeout调用renderImage的时间可说不定，就导致了闪烁。调用的慢的话就能看到，调用的快的话就看不到了。
②vue-excel中还修改了Spreadsheet.sheet.editor.setOffset事件，滚动时就会触发renderImage。

**Comment by bistuly** [comment]
![c](https://github.com/501351981/vue-office/assets/45506275/cf0ad176-2124-4461-8849-54e2798a460b)
