### ISSUE TITLE
不兼容若依项目

### ISSUE THREAD

**Issue by 1501575808** [501351981/vue-office#101]
按照作者和npm官方提供的教程，安装使用后会报错：大概意思时让我安装组合式api，也安装了，还是没成功，升级了vue版本也不可以，目前vue版本是2.6.12

**Comment by 501351981** [comment]
有什么报错要截图看下才知道~~

**Comment by 1501575808** [comment]
解决了，安装组合式api的时候不要最后一个/，正确的安装命令为:npm install @vue/composition-api,然后若依框架在main.js中全局挂载的download要注释掉，就可以正常使用了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月27日(周四) 下午5:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [501351981/vue-office] 不兼容若依项目 (Issue #101)




 
有什么报错要截图看下才知道~~
