### ISSUE TITLE
vue 2.6 项目引入后一片空白

### ISSUE THREAD

**Issue by yangyl568** [501351981/vue-office#103]
运行环境：
浏览器：谷歌浏览器115
vue版本：如vue@^2.6.12
打包工具及版本："webpack": "^4.14.0"

我们有一个基于element-ui 库开发的业务组件库，我想要把这个引进去，
![image](https://github.com/501351981/vue-office/assets/19680934/d6a39775-140b-4295-878a-16f0c5690463)
![image](https://github.com/501351981/vue-office/assets/19680934/041a93b4-e433-48c8-8cec-3d116cfe23a5)

使用之后，一片空白，关键是没有任何报错。
![image](https://github.com/501351981/vue-office/assets/19680934/1c03826d-2dcb-4b42-9896-22420772381f)

**Comment by 501351981** [comment]
如果作为组件库，就别用组件了，由于这个兼容vue2和3，有很多逻辑，建议采用纯js方式预览，见说明文档 https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

**Comment by yangyl568** [comment]
https://github.com/501351981/vue-office/issues/116     这个兄弟跟我遇到的问题一样。

**Comment by ghf1990525** [comment]
> [#116](https://github.com/501351981/vue-office/issues/116) 这个兄弟跟我遇到的问题一样。

请问下兄弟这个问题解决了吗?
