### ISSUE TITLE
引入包之后,控制台会报错The setup binding property "download" is already declared.,怎么解决?

### ISSUE THREAD

**Issue by Mercader1234** [501351981/vue-office#105]
**引入包之后,控制台会报错The setup binding property "download" is already declared.,怎么解决?**

**Comment by Mercader1234** [comment]
开发环境:vue2,web

**Comment by 501351981** [comment]
请下载新版本 1.3.0，download方法重命名为save

**Comment by Mercader1234** [comment]
好的，谢谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月06日 17:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [501351981/vue-office] 引入包之后,控制台会报错The setup binding property "download" is already declared.,怎么解决? (Issue #105) |

请下载新版本 1.3.0，download方法重命名为save
