### ISSUE TITLE
无法预览我的word文件

### ISSUE THREAD

**Issue by xinglu236** [501351981/vue-office#106]
https://mp-ad9dc753-7252-4730-beb0-d003695566b3.cdn.bspapp.com/cloudstorage/zjianli1913.docx
这是我的word文件，无法预览，不知道为什么
[zjianli1913.docx](https://github.com/501351981/vue-office/files/12238460/zjianli1913.docx)

**Comment by xinglu236** [comment]
也不是不能预览，我编辑了一下这个word，新加了一个名字，然后预览，只显示了我刚才加的名字

**Comment by 501351981** [comment]
这个底层用的docx-preivew，我这边没法处理
