### ISSUE TITLE
谷歌浏览器8.4及以下的版本不支持”||=“运算符的问题

### ISSUE THREAD

**Issue by amarsoft7** [501351981/vue-office#109]
组件名称及版本： @vue-office/pdf@1.2.6
运行环境：
浏览器：谷歌浏览器80.0.3987.149（正式版本）
vue版本：vue@2.6.14
问题描述：报错Uncaught SyntaxError: Unexpected token '='，提示window.pdfjsLib未找到，原因是(intentState.renderTasks ||= new Set()).add(internalRenderTask);在ECMAScript 2021之前的JavaScript版本中，使用||=运算符是不被支持。如果要在8.4版本下使用该如何解决这个问题呢

**Comment by 501351981** [comment]
项目基于pdfjs-dist，支持谷歌94+，其他版本不支持哈，暂时没有精力做

**Comment by 501351981** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
