### ISSUE TITLE
预览 pdf 渲染问题

### ISSUE THREAD

**Issue by skming** [501351981/vue-office#112]
组件名称及版本： "@vue-office/pdf": "^1.4.1"
运行环境：
浏览器：手机端 safari
vue版本："vue": "^3.3.4"
打包工具及版本："vite": "^4.4.9"
问题描述：控制台 rendered函数打印 "渲染完成"，pdf为展示灰色内容，再点击其他pdf文件也展示为灰色内容

**Comment by YonChun** [comment]
我也遇到了

**Comment by 501351981** [comment]
是不是浏览器兼容性问题，下载下新版本试试 1.4.2
