### ISSUE TITLE
Excel在有线框的情况下显示空白

### ISSUE THREAD

**Issue by Aaroneee** [501351981/vue-office#113]
1.组件名称及版本： @vue-office/excel": "^1.3.0
2.运行环境：
  浏览器：Edge浏览器 115.0.1901.183 正式版
  vue版本："vue": "^3.3.4"
  打包工具及版本："vite": "^4.4.5"
 Office：office 2013 plus
3.问题描述:
后台创建的Excel文件中有边框样式，前台下载通过后台传过来的Excel也有边框样式，但是使用vue-office/excel展示时却不展示边框样式。

![err](https://github.com/501351981/vue-office/assets/44544164/cfdbd8e8-af8f-4fbe-83d3-14c86a643984)
![errTemp](https://github.com/501351981/vue-office/assets/44544164/ac1072f4-9279-40d7-9602-cb67ba82ec0d)

**Comment by 501351981** [comment]
文件发给我

**Comment by Aaroneee** [comment]
bug已经复现出来了,是因为用了粗边框导致的
![border](https://github.com/501351981/vue-office/assets/44544164/06c40c36-eb87-4c92-8a5b-eb75d9f5f810)
![border-bloder](https://github.com/501351981/vue-office/assets/44544164/1872a6ae-ec08-4657-aadf-613ead7dc602)


[testTemplate.xlsx](https://github.com/501351981/vue-office/files/12319042/testTemplate.xlsx)

**Comment by 501351981** [comment]
显式的修改下边框颜色吧，别用默认主题，获取不到颜色，没法进行预览

**Comment by Aaroneee** [comment]
好的谢谢,试过换成接近于黑色的颜色就可以
