### ISSUE TITLE
excel组件在渲染时是否可以增加loading效果

### ISSUE THREAD

**Issue by jiujiuwu** [501351981/vue-office#114]
组件名称及版本：@vue-office/excel@1.3.0
运行环境：
浏览器：谷歌浏览器
vue版本：vue@2.6.12

问题描述：
在加载数据量大的文件时加载时间也比较长，我遇到的是9000+行数据，加载时间5s左右
这期间excel是以空数据展示的，5s后数据才填充进去

可否在加载数据时增加loading效果，表示正在加载数据

**Comment by 501351981** [comment]
自行添加吧，在render或error事件发生时取消loading
