### ISSUE TITLE
较复杂的pdf文件在移动端渲染不完整速度也很慢

### ISSUE THREAD

**Issue by Sunnshino** [501351981/vue-office#115]
"@vue-office/pdf": "^1.2.6"
运行环境：华为mate30/android（移动端）
"vue": "^2.6.14"
webpack

问题描述：较复杂的pdf文件在移动端渲染不完整速度也很慢
示例地址：https://static-mp-9709b9fe-1df5-469f-86c8-100036681067.next.bspapp.com/

**Comment by 501351981** [comment]
底层用的pdfjs，这个我无法处理

**Comment by Sunnshino** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
