### ISSUE TITLE
vue 2.6.12版本 为什么加载不出来啊 三种都试了

### ISSUE THREAD

**Issue by 451761830** [501351981/vue-office#116]
<img width="960" alt="image" src="https://github.com/501351981/vue-office/assets/48461152/5adbcb71-4a31-4226-8edc-648df9963ade">

里面的节点加载不出来 没有报错

**Comment by 501351981** [comment]
不清楚，试试纯js预览吧，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

**Comment by 501351981** [comment]
检查下网络请求的资源是否成功；控制台是否有一些提醒

**Comment by zhengxs2018** [comment]
@501351981 我同事最近在使用此项目，经过排查，发现在 qiankun 中就会出现这个问题。

他的问题，可能也和此问题类似，都是 jszip 导致的。

@451761830 你可以试试，在 jszip 中的 delay 函数中，打断点调试，看看是不是里面使用的 setImmediate 方法未执行。


我给 qiankun 团队提的 issues：

[[Bug] 乾坤导致 jszip 的 setImmediate 方法不执行](https://github.com/umijs/qiankun/issues/2589)

**Comment by 451761830** [comment]
> @501351981 我同事最近在使用此项目，经过排查，发现在 qiankun 中就会出现这个问题。
> 
> 他的问题，可能也和此问题类似，都是 jszip 导致的。
> 
> @451761830 你可以试试，在 jszip 中的 delay 函数中，打断点调试，看看是不是里面使用的 setImmediate 方法未执行。
> 
> 我给 qiankun 团队提的 issues：
> 
> [[Bug] 乾坤导致 jszip 的 setImmediate 方法不执行](https://github.com/umijs/qiankun/issues/2589)

是的 我也是微应用中使用这个库 显示不了

**Comment by zhengxs2018** [comment]
那你关注下我提给 qiankun 的 issues，这不是这个项目的问题。

不过可以让 @501351981 作者在 readme 中备注下，避免其他人也以为是这个项目问题，而放弃。

我也是第一次知道，目前看这个项目，维护的很不错，好几个同事推荐。

**Comment by zhengxs2018** [comment]
经过重新定位，基本可以确定不是 qiankun 的问题。

@vue-office/docx 内部打包了 jszip，并且可能是 babel 的插件导致 buffer 模块被打包进来

![image](https://github.com/umijs/qiankun/assets/7506913/71c4f5ba-ca87-4a89-b5d4-0fd5b004b140)

![image](https://github.com/umijs/qiankun/assets/7506913/824f2e66-8cbd-4db9-b464-bf2d171d4c44)

导致 jszip 中的 `isNode : typeof Buffer !== "undefined"` 判断为 true

这时传递相对路径，再因为 isNode 为 true，走 jszip 处理，所以走的是 node 端处理。

<img width="225" alt="image" src="https://github.com/umijs/qiankun/assets/7506913/149cbafb-5685-4ae4-8601-8eda8e7bb115">

<img width="515" alt="image" src="https://github.com/umijs/qiankun/assets/7506913/0e8dc914-9639-4a4c-87d2-d18330be1a1b">

如果使用完整的 url，再兼容下 setImmediate ，就没问题，因为不走 jszip 了。

<img width="361" alt="image" src="https://github.com/umijs/qiankun/assets/7506913/106c2559-ae3c-4c2b-a8b2-443a35f8ddc2">

![image](https://github.com/umijs/qiankun/assets/7506913/d1c6c8d8-3b6c-42db-89c4-17f2022d5e2f)

**Comment by 501351981** [comment]
office预览基本原理都是通过jszip读取文件内部的xml文件，应该去除不了

**Comment by 501351981** [comment]
可以直接用docx-preview这个库预览试试，这个项目也是基于这个做的docx预览

**Comment by alleluya-young** [comment]
> 经过重新定位，基本可以确定不是 qiankun 的问题。
> 
> @vue-office/docx 内部打包了 jszip，并且可能是 babel 的插件导致 buffer 模块被打包进来
> 
> ![image](https://user-images.githubusercontent.com/7506913/260411212-71c4f5ba-ca87-4a89-b5d4-0fd5b004b140.png)
> 
> ![image](https://user-images.githubusercontent.com/7506913/260411365-824f2e66-8cbd-4db9-b464-bf2d171d4c44.png)
> 
> 导致 jszip 中的 `isNode : typeof Buffer !== "undefined"` 判断为 true
> 
> 这时传递相对路径，再因为 isNode 为 true，走 jszip 处理，所以走的是 node 端处理。
> 
> <img alt="image" width="225" src="https://user-images.githubusercontent.com/7506913/260412093-149cbafb-5685-4ae4-8601-8eda8e7bb115.png"> <img alt="image" width="515" src="https://user-images.githubusercontent.com/7506913/260411736-0e8dc914-9639-4a4c-87d2-d18330be1a1b.png">
> 如果使用完整的 url，再兼容下 setImmediate ，就没问题，因为不走 jszip 了。
> 
> <img alt="image" width="361" src="https://user-images.githubusercontent.com/7506913/260412341-106c2559-ae3c-4c2b-a8b2-443a35f8ddc2.png">
> ![image](https://user-images.githubusercontent.com/7506913/260412424-d1c6c8d8-3b6c-42db-89c4-17f2022d5e2f.png)

请问下 jszip导致的问题是只有vue-office会空白不显示吗? 像作者说的纯js预览也有这个问题吗? 如果和qiankun无关 为啥演示的文件预览就没问题 在qiankun里是空白?

**Comment by zhengxs2018** [comment]
> 请问下 jszip导致的问题是只有vue-office会空白不显示吗?

前面解释过了。。。。。

1、空白是 jszip 中的 setImmediate 没执行，导致后续代码无法运行，所以才白的。

2、在 qiankun 中出问题，可能是 qiankun 或 qiankun 依赖的某个模块需要 Buffer 对象，导致构建工具将 Buffer 模块打包进来，

![image](https://github.com/501351981/vue-office/assets/7506913/977b5c73-aec5-43b8-9e6c-6d372e28b87d)


![image](https://github.com/501351981/vue-office/assets/7506913/4449161b-2d10-466c-bbac-a192a183b66e)

**Comment by JackShijt** [comment]
我是micro-app，也遇到了这个问题，目前无解吗？docx-preview也是一片空白。excel和pdf都是正常的，只有docx显示不了，控制台没有任何打印。

**Comment by 501351981** [comment]
感谢兄弟们的意见，已经尝试修复
