### ISSUE TITLE
pdf预览能不能做宽度自适应父级宽度

### ISSUE THREAD

**Issue by xiechunyang** [501351981/vue-office#117]
内容总是超出父级，切不能控制宽度，样式不美观

**Comment by loungers** [comment]
翻源码，源码里做了处理，可以在组件引用时 增加options绑定，绑定对象里面传入width就行 
![image](https://github.com/501351981/vue-office/assets/58649899/98d5b669-5b41-4153-842b-9e7ea3e789a6)

**Comment by lianxin255** [comment]
讲道理，外层包裹容器设置宽度不就好了。

**Comment by 501351981** [comment]
已解决

**Comment by 94ashui** [comment]
> 已解决

这个怎么解决的呢。
