### ISSUE TITLE
@vue-office/pdf@1.4.2 依赖vue-demi@"^0.13.11"版本过低

### ISSUE THREAD

**Issue by yeastone** [501351981/vue-office#119]
组件名称及版本： @vue-office/pdf
运行环境：
浏览器：谷歌浏览器
vue版本：如vue@2.6.14
打包工具及版本：
问题描述：
**vue-demi 最新版本与 @vue-office/pdf@1.4.2依赖版本冲突**

npm ERR! Found: vue-demi@0.14.5
npm ERR! node_modules/vue-demi
npm ERR!   vue-demi@"^0.14.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue-demi@"^0.13.11" from @vue-office/pdf@1.4.2
npm ERR! node_modules/@vue-office/pdf
npm ERR!   @vue-office/pdf@"^1.4.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

**Comment by 501351981** [comment]
那先手动安装老版本？

**Comment by yeastone** [comment]
感谢回复，
把vue-demi 降到0.13.11后会报错 vue 版本不匹配
这可能是我的问题
Error: 
Vue packages version mismatch:
 This may cause things to work incorrectly. Make sure to use the same version for both.
        If you are using vue-loader@>=10.0, simply update vue-template-compiler.
        If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by 501351981** [comment]
package.json中将vue-demi版本固定，删除package.lock.json，删除node_modules目录，重新安装所有包看看
