### ISSUE TITLE
docx文件和pdf文件的灰色的背景颜色能去掉吗

### ISSUE THREAD

**Issue by xiaotuling2021** [501351981/vue-office#121]
<img width="1490" alt="image" src="https://github.com/501351981/vue-office/assets/82923804/a2f4b1de-ea6b-411e-b508-7f5385eab495">
docx文件和pdf文件的灰色的背景颜色能去掉吗

**Comment by zhangxc666** [comment]
修改padding应该可以解决

**Comment by 501351981** [comment]
css修改背景色为白色
