### ISSUE TITLE
部分情况下，预览超过100行的excel文件时，只显示100行

### ISSUE THREAD

**Issue by ercy12138** [501351981/vue-office#122]
使用` @vue-office/excel@1.4.0`预览excel文件，文件在102行还有数据，但是页面的表格只显示100行。

查看代码发现，预览表格展示的行数是来自在`js-excel/src/main.js`中的transferExcelToSpreadSheet函数,取`sheetData.rows.length`与100之间的最大值:
![image](https://github.com/501351981/vue-office/assets/64447610/de878117-49a6-42c7-a9c7-21b4491c5324)

查看控制台输出的workbook，发现这份excel文件的84行到100行这些空行是不再_rows数组中的，导致`sheetData.rows`的长度小于100，使得预览展示的表格只显示100行：
![image](https://github.com/501351981/vue-office/assets/64447610/75a65490-3726-4dc0-a9f6-02ef0dfc37b8)
但是_rows数组本身的length属性值为106，因此是不是直接取`_rows.length`与100比较，来决定页面表格需要展示的行数比较好？

**Comment by 501351981** [comment]
抽空解决

**Comment by 501351981** [comment]
@vue-office/excel@1.4.1
