### ISSUE TITLE
TypeError: Cannot read property 'GlobalWorkerOptions' of undefined

### ISSUE THREAD

**Issue by Wangmbo** [501351981/vue-office#123]
源码： 
![image](https://github.com/501351981/vue-office/assets/57891230/762896ad-8d4b-4274-a0b0-730f535da997)

错误信息：
![image](https://github.com/501351981/vue-office/assets/57891230/099124aa-eb0f-4f68-9d7a-463de54ed8c2)

**Comment by 501351981** [comment]
浏览器版本多少

**Comment by Wangmbo** [comment]
> 浏览器版本多少

可能跟浏览器版本无关，估计是因为在electron运行的原因？
