### ISSUE TITLE
使用Excel组件进行阅览的时候，点击单元格并且进行ctrl+c无法复制，单元格数据

### ISSUE THREAD

**Issue by JYNJBN** [501351981/vue-office#124]
组件名称及版本： 如@VueOfficeExcel 1.40
运行环境：
浏览器：谷歌浏览器
vue版本："vue": "3.2.47",
打包工具及版本："vite": "3.2.7",
问题描述：点击单元格并且进行ctrl+c无法复制，选中的单元格中的数据
将excel文件导入https://501351981.github.io/vue-office/examples/dist/#/excel 时却可以正常复制单元格中的数据
![image](https://github.com/501351981/vue-office/assets/84171317/897c1f08-d6a5-4296-a694-45fa376b09a4)
![image](https://github.com/501351981/vue-office/assets/84171317/675f7997-7733-4cf0-ba77-56fb235374cf)

**Comment by JYNJBN** [comment]
哪位大佬可以解答一下

**Comment by bistuly** [comment]
没能重现，demo没问题 你提issues也没用呀，谁还能替你改bug啊。 可能原因 ①是不是在组件的click事件中做了一些骚操作，父组件或者根组件有没有拦截或者处理按键事件 ②检查下excel文件。
