### ISSUE TITLE
Pdf预览，渲染失败 TypeError: Cannot read properties of undefined (reading 'getContext')

### ISSUE THREAD

**Issue by loao** [501351981/vue-office#126]
本地环境：
<img width="990" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/d4fa06bd-88fb-4f31-9d3c-621d16bba3f9">

相关代码：
<img width="734" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/e3f60609-e690-46ff-8980-f2187b5a104e">
<img width="547" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/72d9b554-dc64-4117-94ec-039fb8d57828">
<img width="364" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/2bf914a7-c7ff-4c0e-8f68-868555fac801">

调试结果：
<img width="790" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/475e4f5a-3a97-40bc-acf9-8575471e016e">
<img width="1094" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/c5bc2d87-10d3-4f5a-9393-11d97c6f77c5">
<img width="1115" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/b31cba61-830b-4477-a2f1-e20381bd6989">

**Comment by loao** [comment]
页面显示效果：
<img width="969" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/86ead044-6ece-4b71-b3da-b520ad811446">

**Comment by 501351981** [comment]
1.5.1，看看还有问题吗

**Comment by shanjixiaboss** [comment]
> 1.5.1，看看还有问题吗

测试了vue 2.6.10下应该是下面这处有问题，canvas没取到节点

![image](https://github.com/501351981/vue-office/assets/12005707/6795a6ad-cc45-475e-99f0-85e0a2e6f238)

**Comment by wgh970312** [comment]
问题还存在，试了1.6.0和1.5.5

**Comment by Wo-com** [comment]
我也遇到了问题还存在，试了1.6.5和1.5.5
预览PDF文件报错
TypeError: Cannot read properties of undefined (reading 'getContext')
