### ISSUE TITLE
使用组件vue-office-excel打包后报错

### ISSUE THREAD

**Issue by xingaa** [501351981/vue-office#129]
版本"@vue-office/excel": "^0.2.6",
组件vue-office-excel 
本地开发没有问题，打包后访问报出下面问题
![image](https://github.com/501351981/vue-office/assets/71254107/0762d63b-b824-49ce-8140-0f9fa42decc7)

**Comment by 501351981** [comment]
参考文档：https://501351981.github.io/vue-office/examples/docs/guide/faq.html#definecomponent-is-not-a-function
