### ISSUE TITLE
在弹出对话框中预览Excel，初始化的宽高尺寸计算有问题

### ISSUE THREAD

**Issue by loao** [501351981/vue-office#130]
如图：
1.这是对话框弹出后的初始状态
<img width="1439" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/93bd2098-f30b-4351-a839-c1c007f45823">

2.这是在展示的Excel中使用鼠标滚动后的状态
<img width="1435" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/d5479b8a-4fdd-4a8b-92a1-b1a6192b7003">

3.此时，我再调出调试窗口后的状态
<img width="1438" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/5719cd0b-c81b-418d-a343-91cc16dabd55">

4.这是我关闭调试窗口后的状态
<img width="1439" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/cf4f986c-5911-44e4-9502-b5fb98d2dce6">

通过上面的测试，感觉问题应该是在第一次获取页面窗口大小的数据上有偏差，通过后面几次改变页面窗口后，才是数据恢复正常。

**Comment by loao** [comment]
2.这是在展示的Excel中使用鼠标滚动后的状态
<img width="1438" alt="image" src="https://github.com/501351981/vue-office/assets/26564409/57c58f7c-bb5f-484c-a39d-5a2a15a4aef4">

**Comment by 501351981** [comment]
延迟下加载吧，弹窗dom没渲染好吧
