### ISSUE TITLE
预览报错is this a zip file ? if it is

### ISSUE THREAD

**Issue by bierenjiadehaizi** [501351981/vue-office#133]
1.组件名称及版本： @vue-office/docx 1.3.0
2.运行环境：浏览器：如谷歌浏览器77版本
vue版本：vue@2.6.11
3打包工具及版本：vue-cli@4.2.0
4问题描述：预览报错is this a zip file ? if it is 换了非Vue框架文件预览@js-preview/docx也是报这个错误

**Comment by 501351981** [comment]
是doc格式文件吗，不支持doc格式文件
