### ISSUE TITLE
js word 在angular15中启动报错误

### ISSUE THREAD

**Issue by zhoubonet** [501351981/vue-office#136]
<img width="710" alt="image" src="https://github.com/501351981/vue-office/assets/4209701/bd19e603-ef1c-4f5d-820a-e1a726b6311d">

**Comment by zhoubonet** [comment]
<img width="721" alt="image" src="https://github.com/501351981/vue-office/assets/4209701/193cfb45-9f72-47eb-a7ba-7554ca60864d">
两个错误,方便看看吗？

**Comment by 501351981** [comment]
报错信息里面已经给出方案了，在webpack配置的resolve中添加几行代码就行了

module.exports = {
  //...
  resolve: {
    fallback: {
       stream: fakse,
       util:false
    },
  },
};

**Comment by zhoubonet** [comment]
已经解决了
