### ISSUE TITLE
请问，有计划支持读取带密码加密的xlsx格式的excel文件吗？

### ISSUE THREAD

**Issue by zurmokeeper** [501351981/vue-office#138]
请问，有计划支持读取带密码加密的xlsx格式的excel文件吗？

**Comment by 501351981** [comment]
这个不支持哈，依赖的第三方库不支持

**Comment by zurmokeeper** [comment]
@501351981 https://github.com/zurmokeeper/excelize 可以看下这个项目，完全兼容exceljs v4.3.0，支持docx,pptx,xlsx,xls解密
