### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by m13886695261** [501351981/vue-office#139]
太难了 哥们怎么强制懒加载啊 首次加载五页 根本不给一点自己做分页或者全加载的机会
像我二十来页的pdf 想截去第一页一点机会没有 能给点配置的机会吗

**Comment by 501351981** [comment]
最新版本： @vue-office/pdf@1.5.3
其次：固定之前版本不就行了，这有什么可抱怨的

**Comment by 501351981** [comment]
最新版本： @vue-office/pdf@1.5.3
其次：固定之前版本不就行了，这有什么可抱怨的
