### ISSUE TITLE
excel组件渲染后跟原始excel文件不一致

### ISSUE THREAD

**Issue by CJ-Zheng1023** [501351981/vue-office#14]
组件名称及版本： 如@vue-office/excel@0.1.4
运行环境：
浏览器：electron/chromium
vue版本：如vue@2.7.14
打包工具及版本：如webpack@5.75.0
excel截图
![excel截图](https://user-images.githubusercontent.com/13232989/220555877-3b9eb2a3-b0f5-4b6c-b94d-780971be1a74.PNG)

渲染后的截图
![组件渲染后的截图](https://user-images.githubusercontent.com/13232989/220555886-43b3d70c-3d0f-46c0-b4f8-1e8938d03da6.PNG)

附excel
[1.xlsx](https://github.com/501351981/vue-office/files/10801710/1.xlsx)

**Comment by 501351981** [comment]
收到

**Comment by 501351981** [comment]
部分解决，版本 0.2.0
不过excel一些颜色值没法完全一致，暂时无界

**Comment by CJ-Zheng1023** [comment]
> 部分解决，版本 0.2.0 不过excel一些颜色值没法完全一致，暂时无解

感谢~
