### ISSUE TITLE
移动端文本类型展示不全&& pc端字体大小不一致

### ISSUE THREAD

**Issue by webyushao** [501351981/vue-office#141]
组件名称及版本： @vue-office/excel": "^1.4.5",
运行环境：
浏览器：谷歌浏览器
vue版本：vue@2.6.10
打包工具及版本：vue-cli
问题描述： PC端字体大小显示不一致。
                    移动端文本类型展示不全。

**Comment by 501351981** [comment]
给宽高加点偏移量吧，很难做到完全一致，把宽高加大点，展示全。
https://501351981.github.io/vue-office/examples/docs/config/#options

widthOffset：在默认渲染的列表宽度上再加10px宽

heightOffset：在默认渲染的列表高度上再加10px高
