### ISSUE TITLE
有支持doc格式的文件的计划么

### ISSUE THREAD

**Issue by moyu284** [501351981/vue-office#142]
有支持doc格式的文件的计划么

**Comment by zurmokeeper** [comment]
@moyu284 想问下前端要处理或者展示word的场景多吗？比如什么场景。

**Comment by 501351981** [comment]
目前基本没有纯前端预览doc的方案，所以也没法支持

**Comment by moyu284** [comment]
> @moyu284 想问下前端要处理或者展示word的场景多吗？比如什么场景。

我这边是有上传doc或者docx文档，然后想在线预览来着
