### ISSUE TITLE
与vue@2.6.10版本不兼容

### ISSUE THREAD

**Issue by akaashmyth** [501351981/vue-office#144]
1. 组件名称及版本：@vue-office/excel: "^1.4.5"，@vue-office/docx: "^1.3.0"，@vue/composition-api": "^1.7.2"
2. 运行环境：谷歌浏览器v116.0.5845.141
3. vue版本：vue@^2.6.10，vue-template-compiler: "^2.5.17"
4. 打包工具及版本：@vue/cli-service: "^3.1.4"
5. 问题描述：使用docx和excel组件，引用后运行本地项目，报错包版本不兼容。当前是vue-template-compiler不兼容，升级后又会报其他的依赖包不兼容
![image](https://github.com/501351981/vue-office/assets/3435267/ba322b69-4d14-4a48-8dac-7e4be09c316a)

**Comment by 501351981** [comment]
vue和vue-template-compiler 版本要保持一致啊

**Comment by akaashmyth** [comment]
@501351981 可以了，感谢
