### ISSUE TITLE
解析2006版本word不可以

### ISSUE THREAD

**Issue by zkyeu** [501351981/vue-office#149]
解析2006版本的word不行啊。
![image](https://github.com/501351981/vue-office/assets/11844997/b37f25b2-4d00-42ed-8082-3626fc7d5696)

本来word是这样的：
![image](https://github.com/501351981/vue-office/assets/11844997/9a86e615-74d6-4522-80d5-79bab1182021)

解析后变这样子了：
![image](https://github.com/501351981/vue-office/assets/11844997/f2dd4e6d-0e5a-40b9-858b-ea154ded9a17)

word 地址：https://zyb-tiku-scanbook-1253445850.cos.ap-beijing.myqcloud.com/private/demo/wenda.docx

**Comment by 501351981** [comment]
确实如此，不过我也没有办法解决，这个依赖的docx-preview，解析出来就是这样，最好能转成pdf预览吧，word预览效果普遍没有pdf好
