### ISSUE TITLE
开启lazy加载 5 页，但是下拉不继续加载了

### ISSUE THREAD

**Issue by biezhenyu** [501351981/vue-office#150]
<vue-office-pdf
      :src="src"
      style="height: 0; flex: 1"
      :options="{ lazy: true }"
      @rendered="rendered"
      @error="errorHandler"
    />
     用的blob格式的文件
     
     vue": "^3.2.13
     @vue-office/pdf": "^1.5.3"
     插件版本
     不开懒加载没问题，但是嵌套 app 会崩溃，尝试使用懒加载，开启之后加载 5 页，下滑没有重新加载

**Comment by 501351981** [comment]
组件外面设个高度，能让组件发生滚动

**Comment by biezhenyu** [comment]
不好意思，再打扰 一下，我外层已经设置 高度，也尝试了里面的方法还是不行
 <div class="pdf">
    <vue-office-pdf
      :src="src"
      :options="{ lazy: true }"
      @rendered="rendered"
      @error="errorHandler"
    />
  </div>
  .pdf {
  height: 100vh;
}
:deep(.vue-office-pdf) {
  height: 100% !important;
}

**Comment by biezhenyu** [comment]
> 参考下别人的解决方法吧，#131

不好意思，我设置有高度，也参考了 131 里面还是不行
` <div class="pdf">
    <vue-office-pdf
      :src="src"
      :options="{ lazy: true }"
      @rendered="rendered"
      @error="errorHandler"
    />
  </div>`
`.pdf {
  height: 100vh;
}
:deep(.vue-office-pdf) {
  height: 100% !important;
}`

**Comment by 501351981** [comment]
不太清楚，可以试试加overflow-y呢？也只是猜测了
.pdf {
height: 100vh;
overflow-y: scroll;
}

**Comment by biezhenyu** [comment]
好的，谢谢啦，我现在是在浏览器调试，但是我发现我尝试在滑动到底部的时候再控制太去掉 height：100%，他就能加载一页
<img width="649" alt="image" src="https://github.com/501351981/vue-office/assets/23213442/4d54d7a1-e610-4093-8b71-ffcf28357c71">

**Comment by 501351981** [comment]
代码贴出来看看吧

**Comment by 501351981** [comment]
截图里面没看到你上面说的.pdf样式
