### ISSUE TITLE
uniapp vue2 版本中使用报错，找不到相关文件

### ISSUE THREAD

**Issue by persiliao** [501351981/vue-office#151]
组件名称及版本： @vue-office/docx@1.3.0
运行环境：
浏览器：Google Chrome
vue版本: vue@2.6.x
打包工具及版本：uniapp 是webpack
问题: 

'@vue/composition-api/dist/vue-composition-api.mjs' at node_modules/vue-demi/lib/index.mjs:338

```json
{
  "dependencies": {
    "@vue-office/docx": "^1.3.0",
    "@vue/composition-api": "^1.7.2",
    "vue-demi": "0.13.11",
  }
}
```

**Comment by 501351981** [comment]
不太清楚，可以换个库调用，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

**Comment by persiliao** [comment]
嗯，之后换成这个可以正常预览了
