### ISSUE TITLE
vue2版本excel打开报错

### ISSUE THREAD

**Issue by zuobaiquan** [501351981/vue-office#154]
vue2版本excel打开报错
![图片](https://github.com/501351981/vue-office/assets/17662026/c73abc7d-82be-4d2f-9e99-c356dce6ba67)

**Comment by zuobaiquan** [comment]
有没有大佬遇到过，而且不支持图片预览 返回[Object Object]

**Comment by 501351981** [comment]
是图片吗？jpg jpeg png等图片格式
