### ISSUE TITLE
:options="{lazy:true}" 配置了懒加载，pdf预览到第5页就到底没办法再加载了

### ISSUE THREAD

**Issue by h3m4** [501351981/vue-office#156]
组件名称及版本： @vue-office/pdf@1.5.3
运行环境：
浏览器：谷歌浏览器
vue版本：vue@2.6.0
问题描述：:options="{lazy:true}" 配置了懒加载，pdf预览到第5页就到底没办法再加载了，麻烦大佬解答下

**Comment by 501351981** [comment]
给组件加个高度，让其内部能发生滚动，可以参考 https://github.com/501351981/vue-office/issues/131
