### ISSUE TITLE
excel渲染加载异常bug

### ISSUE THREAD

**Issue by zhangbaojia** [501351981/vue-office#161]
实际场景是在一个签页容器中渲染excel ；
问题：
 1、刷新浏览器如果不是选中的是默认excel所在签页，这时候切换到excel的时候不是100%高度，如下图"运行异常"，
 2、在正常渲染时如果不在onMounted中设置下等待后端将数据全部返回也是这种现象，
 3、即便是后面数据加载上，也自动全部渲染完也不能选择下面再次渲染的内容。

运行效果：
![excel](https://github.com/501351981/vue-office/assets/19427334/832b2881-7f75-4d1f-9a21-d7278aa52a1c)

运行异常
![image](https://github.com/501351981/vue-office/assets/19427334/f55a5418-30ac-42bc-88c9-2714faebe6e2)

运行正常
![image](https://github.com/501351981/vue-office/assets/19427334/90ca59bc-c901-4187-91c1-76b2bc085401)

**Comment by 501351981** [comment]
切换到某个页签后，延迟100ms再渲染组件看看

**Comment by zhangbaojia** [comment]
是的，上面的效果是已经设置500ms后的效果了。

**Comment by zhangbaojia** [comment]
@501351981 还有其它优化方案吗？
