### ISSUE TITLE
excel 显示问题

### ISSUE THREAD

**Issue by luomaohao** [501351981/vue-office#164]
组件名称及版本： js-preview/excel
运行环境：
浏览器：如谷歌浏览器
react
打包工具：webpack
问题描述：用了测试demo中excel文件，测试文件中图片溢出到第一个sheet。
![屏幕截图 2023-10-12 172042](https://github.com/501351981/vue-office/assets/36148933/c0f076f9-4970-4a21-bc8c-f6bd218c0a29)

**Comment by 501351981** [comment]
好的，有时间我看看
