### ISSUE TITLE
excel显示问题

### ISSUE THREAD

**Issue by mengpierde** [501351981/vue-office#167]
@vue-office/excel": "^1.4.5
运行环境：Chrome 117.0.5938.152
"vue": "^2.7.14"
webpack

excel原文件通过函数计算的的结果在系统预览时无法正常解析
<img width="206" alt="1697434279689_C7493108-0685-4885-A556-8442A8919BDD" src="https://github.com/501351981/vue-office/assets/45477141/c7639ed6-ca73-4b49-9c88-b5b199ce74e2">

**Comment by 501351981** [comment]
最好是将这一列设为文本，省的各种数据格式转换

**Comment by mengpierde** [comment]
好的 歇歇
