### ISSUE TITLE
500多行的xlsx文件,无法正常预览,且宽度无法自适应

### ISSUE THREAD

**Issue by hahalxy** [501351981/vue-office#17]
版本: '@vue-office/excel': 0.1.6

500多行的文件预览时报错
报错如下:
![1677744177632](https://user-images.githubusercontent.com/126760482/222369385-1cc3a76c-dcd4-44aa-b697-003242910613.png)

宽度无法自适应问题
![image](https://user-images.githubusercontent.com/126760482/222369912-ee3a858f-33e1-405a-9f07-232da3c09423.png)

ps: 
'@vue-office/docx' 目前正常使用,好评
'@vue-office/pdf'如果能加上放大缩小功能就更好了

**Comment by 501351981** [comment]
使用最新版本吧0.2.2

**Comment by hahalxy** [comment]
已升级到0.2.2,
还是存在上述问题

**Comment by 501351981** [comment]
excel文件发我一下吧 微信 \_hit757_

**Comment by 501351981** [comment]
done
