### ISSUE TITLE
 "@vue-office/pdf": "^1.5.4",内存溢出了

### ISSUE THREAD

**Issue by horizon188** [501351981/vue-office#170]
![image](https://github.com/501351981/vue-office/assets/37240607/dd583f28-1caa-4157-8395-393bfa85ff88)
占用内存了

**Comment by horizon188** [comment]
![image](https://github.com/501351981/vue-office/assets/37240607/b8b12d6a-63b2-4e90-87dd-a2acb0b6a122)

**Comment by horizon188** [comment]
worker可以配置销毁停止吗？Worker.terminate()

**Comment by wqudhqdh** [comment]
这个问题解决了吗

**Comment by horizon188** [comment]
> 这个问题解决了吗

楼主是弄了一个局，让我们付费给钱，再给包，没想最后大家都抛弃了，换包吧，要用的话就改一下包的代码

**Comment by horizon188** [comment]
本来想自己pdfjs写，发现vue3-pdf-app真香

**Comment by yangyang8599** [comment]
我也遇到这个问题，内存暴涨，切换unmounted后内存依然没有释放。现在有解决吗？

**Comment by yangyang8599** [comment]
经过反复测试，确定使用blob时，内存没有正确释放，反复预览大约20次以上，会出现内存移除（次数多少取决于电脑内存大小）

我只测试了blob没有测试其他形式的src数据。

**Comment by ShowMeBaby** [comment]
我也遇到了相同的问题, 有人有解决方案吗

**Comment by 501351981** [comment]
> > 这个问题解决了吗
> 
> 楼主是弄了一个局，让我们付费给钱，再给包，没想最后大家都抛弃了，换包吧，要用的话就改一下包的代码

谁收你一分钱了？张嘴就来

**Comment by 501351981** [comment]
已修复 1.6.0版本
