### ISSUE TITLE
iOS PDF不行。

### ISSUE THREAD

**Issue by yanhao98** [501351981/vue-office#171]
docx和excel是可以的。

![image](https://github.com/501351981/vue-office/assets/37316281/86ffcdc7-4599-4ebd-91bb-27c5d5aa7f99)

**Comment by X-WC** [comment]
解决了吗

**Comment by yanhao98** [comment]
> 解决了吗

让产品把业务改了。

**Comment by cvpv** [comment]
这是一个严重的问题啊!

**Comment by cvpv** [comment]
使用前端来实现文档预览是不是一个伪命题？是不是应该使用类似kkfileview之类的后端库来实现更易于管理

**Comment by Alibaba-Jarry** [comment]
如何解决

**Comment by 501351981** [comment]
我的demo并不支持，直接用库，自行打包测试，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html
