### ISSUE TITLE
excel里的饼图文字和图形解析错误

### ISSUE THREAD

**Issue by woogoy** [501351981/vue-office#176]
组件名称及版本：  @vue-office/excel
运行环境：
浏览器：谷歌浏览器
测试工具：https://501351981.github.io/vue-office/examples/dist/#/excel
问题描述：（如果有报错，麻烦粘贴详细的报错信息、package.json内容等）

    通过上面测试工具网站导入的本地excel文件，首页底部的饼图表解析不出来，“共扫描出:”后面的文字也丢失了。测试文件如下：
[applications_xxxx.xlsx](https://github.com/501351981/vue-office/files/13184494/applications_xxxx.xlsx)
  解析出错：
![image](https://github.com/501351981/vue-office/assets/1765525/ea59a00f-5408-4679-a5d3-1a94434b9580)
  正确应该如下：
![image](https://github.com/501351981/vue-office/assets/1765525/a5c36acb-d51a-4914-a54d-d83a837699be)

**Comment by 501351981** [comment]
不支持图形的预览
