### ISSUE TITLE
Excel渲染问题

### ISSUE THREAD

**Issue by TongKaiQiang** [501351981/vue-office#177]
1、组件名称版本："@vue-office/excel": "^1.4.5"
2、运行环境：谷歌浏览器【Chrome 已是最新版本 119.0.6045.106（正式版本） （64 位）】
3、Excel渲染问题，线条没有出来
正常打开：
![image](https://github.com/501351981/vue-office/assets/12757040/60f036c1-22ba-46e2-b163-d1694f5f65f4)

vue-office/excel打开：
![image](https://github.com/501351981/vue-office/assets/12757040/46116b68-7cab-4f6b-8429-59fdf29bad9e)

**Comment by 501351981** [comment]
是否是用word操作的，还是wps的，正常配置边框没有问题

**Comment by TongKaiQiang** [comment]
word操作的啊

**Comment by PY1122** [comment]
你好，请问这个问题解决了吗  我使用的1.4.7  Excel 也是没有框框的线条

**Comment by TongKaiQiang** [comment]
@PY1122 未解决，这个需要让作者去解决 @501351981
