### ISSUE TITLE
vue-office/pdf 执行tsc:check 报错

### ISSUE THREAD

**Issue by zhangsijun975999** [501351981/vue-office#179]
![微信截图_20231108113118](https://github.com/501351981/vue-office/assets/44431377/14cad9c5-f6ac-427c-9679-42a9f7d4dedf)目前发现rerender这个方法加个可空之后check通过，但是这个方法传了也无法通过check，没看懂此方法用处，不是主攻前端，求助各位大佬
其他两个组件没问题

**Comment by 501351981** [comment]
我发布了一个新版本，再试试， @vue-office/pdf@1.5.5
