### ISSUE TITLE
vue3+vite4+ts无法import组件

### ISSUE THREAD

**Issue by divq** [501351981/vue-office#18]
组件名称
    `"@vue-office/docx": "^0.2.2",`
    `"@vue-office/excel": "^0.2.3",`

Vue和Vite版本：
   `"vue": "^3.2.45",`
   `"vite": "^4.1.0",`

`import VueOfficeExcel from '@vue-office/excel'`
或者
`import VueOfficeExcel from '@vue-office/docx'`
时报错，提示说：
```typescript
TS7016: Could not find a declaration file for module '@vue-office/excel'. 

'/Users/xxx/node_modules/@vue-office/excel/lib/index.js' implicitly has an 'any' type.   

Try `npm i --save-dev @types/vue-office__excel` if it exists or add a new declaration (.d.ts) file containing `declare module '@vue-office/excel';`
```

如果 `npm i --save-dev @types/vue-office__docx`， 或者`npm install -D @types/vue-office`
， 提示`not found`

**Comment by 501351981** [comment]
试试 0.2.4版本吧

**Comment by 501351981** [comment]
如果没有问题，暂时关闭了
