### ISSUE TITLE
vue-office 渲染异常不报成功也不报失败

### ISSUE THREAD

**Issue by gitzyj** [501351981/vue-office#180]
情况是我想扩展功能，在a项目中 引用了vue-office 相关组件，打包成了npm 包。在b项目 引入了这个a npm。进行使用。
结果就是 不会正常渲染 node 12.18.0 vue 2.6.14
rendered error 回调不触发
黑底 
![4271699516570_ pic](https://github.com/501351981/vue-office/assets/46037140/7ee70126-a976-493a-8c9d-86cb034fa6e8)

vue-office-docx-main 节点 空的
![4281699516615_ pic](https://github.com/501351981/vue-office/assets/46037140/07d8212a-24b1-4c1b-b181-318299b54efa)

**Comment by 501351981** [comment]
建议使用纯js方式使用，组件方式涉及兼容vue2/3，比较复杂，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

**Comment by gitzyj** [comment]
> 建议使用纯js方式使用，组件方式涉及兼容vue2/3，比较复杂，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

import jsPreviewDocx from "@js-preview/docx";  jsPreviewDocx undefined

**Comment by gitzyj** [comment]
> 建议使用纯js方式使用，组件方式涉及兼容vue2/3，比较复杂，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

js 有cdn 连接用包引 打包会报错

**Comment by 501351981** [comment]
这个和CDN有什么关系？
