### ISSUE TITLE
Cannot merge already merged cells

### ISSUE THREAD

**Issue by float008** [501351981/vue-office#191]
在React中使用，报错信息 Cannot merge already merged cells

**Comment by float008** [comment]
![image](https://github.com/501351981/vue-office/assets/93424574/cb039a66-4cc7-4fb6-a577-c2d238576d30)
 myExcelPreviewer.preview(href) 数据是从后端请求的

**Comment by 501351981** [comment]
看看是不是文件有问题吧，用excel软件打开

**Comment by float008** [comment]
文件打开也是没问题的

**Comment by float008** [comment]
官网demo演示也存在这个问题。看了下，好像现在预览excel并不支持已经合并单元格的文件
