### ISSUE TITLE
预览报错：Cannot merge already merged cells  

### ISSUE THREAD

**Issue by float008** [501351981/vue-office#192]
在官网Demo也存在同样的情况，已经合并单元格的excel文件在预览时会报错
![image](https://github.com/501351981/vue-office/assets/93424574/2cecc23c-0999-4ea6-bc89-7dc6ed358ba0)
在其他的issues也存在类似情况。大佬这是bug吗？还是说暂不支持合并单元格excel文件的预览。

**Comment by float008** [comment]
[demo.xlsx](https://github.com/501351981/vue-office/files/13642768/demo.xlsx)
excel打开没问题

**Comment by 501351981** [comment]
![Uploading WX20231213-182718@2x.png…]()

**Comment by 501351981** [comment]
<img width="287" alt="WX20231213-182718@2x" src="https://github.com/501351981/vue-office/assets/14229082/3251e73d-93fc-48c4-aaa9-2c2a601c094e">

**Comment by 501351981** [comment]
你是用的WPS吧，不是Excel
