### ISSUE TITLE
README.md 关于安装这一步骤的坑

### ISSUE THREAD

**Issue by DavissonA9** [501351981/vue-office#193]
如果是vue2.6版本或以下还需要额外安装 @vue/composition-api
npm install @vue/composition-api/

坑爹呢,  一个不小心直接复制了, 就
`npm ERR! Could not install from "@vue\composition-api" as it does not contain a package.json file`

npm install @vue/composition-api/ 结尾的 / 是真的真的正确的吗?

**Comment by 501351981** [comment]
提问题好好提，说话不干不净的，我说坑儿子呢，你爱听吗？
