### ISSUE TITLE
Excel渲染报错，无法显示

### ISSUE THREAD

**Issue by TongKaiQiang** [501351981/vue-office#195]
https://501351981.github.io/vue-office/examples/dist/#/excel
1、@vue-office/excel@最新版
2、运行环境：谷歌浏览器
3、预览Excel无法显示，控制台报错，直接在你这个Demo上演示报错的
![image](https://github.com/501351981/vue-office/assets/12757040/eed44505-8f2f-467a-a070-5ac01dbd39c2)
![image](https://github.com/501351981/vue-office/assets/12757040/472b2e8c-b698-4d81-875e-82155fc9dba9)

**Comment by 501351981** [comment]
不是说后缀是.xlsx就是真的xlsx格式，xls不能改下后缀变成别的格式，报错应该就是格式不对
