### ISSUE TITLE
渲染excel表格时，合并的单元格(某些列单元格长短不一)会导致渲染异常，变成窄窄的一条线，造成内容显示不全

### ISSUE THREAD

**Issue by mangy1** [501351981/vue-office#197]
官网示例就可复现该问题。

![image](https://github.com/501351981/vue-office/assets/67996468/7c442783-71d2-4fad-9897-52f03bc226d6)
上图是本地正常打开时的excel
![image](https://github.com/501351981/vue-office/assets/67996468/781ee092-b9f9-4f4f-8399-62974c8aaf73)
以上是官网示例加载的效果

附件为测试用的excel：
[1700618521605124_VEO_FORM_12_QC済.xlsx](https://github.com/501351981/vue-office/files/13711950/1700618521605124_VEO_FORM_12_QC.xlsx)

**Comment by 501351981** [comment]
表格内的文字大小才10，至少设个12吧，确实表格高度就是不高，exceljs读取出来就12多像素高
