### ISSUE TITLE
window.pdfjsLib未找到

### ISSUE THREAD

**Issue by gf13223436** [501351981/vue-office#199]

**Comment by gf13223436** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by gf13223436** [comment]
实际咋解决

**Comment by dh336699** [comment]
@501351981 你好, 这个问题有解决吗

**Comment by gf13223436** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
