### ISSUE TITLE
可否考虑增加doc格式支持

### ISSUE THREAD

**Issue by chenyy66** [501351981/vue-office#2]
感谢作者提供这么好用的组件库，在使用该组件时，貌似不支持doc格式的文档，可否考虑增加doc格式的支持？

**Comment by 501351981** [comment]
看看其他人需求，毕竟不是主流了

**Comment by yuluod** [comment]
希望能够新增对于doc格式的支持。

**Comment by 501351981** [comment]
在github里面搜了很多，没有找到doc预览方案，有方案的可以提供下，我集成进去~~
