### ISSUE TITLE
使用excel预览显示渲染失败

### ISSUE THREAD

**Issue by Aromashen** [501351981/vue-office#201]
组件名称及版本： @vue-office/excel": "^1.6.0"
运行环境：
浏览器：谷歌浏览器
vue版本：如vue@2.6.11
打包工具及版本：如webpack
问题描述：预览excel调用error 显示渲染失败      使用方式<vue-office-excel :src="excel" style="height: 500px;width:100vw" @error="errorHandler"/>

**Comment by 501351981** [comment]
error信息呢？ 目前不支持xls格式预览
