### ISSUE TITLE
选择本地PDF文件预览,pdf文件打开显示空白

### ISSUE THREAD

**Issue by webzmj530** [501351981/vue-office#207]
1、组件名称及版本： 如"@vue-office/pdf": "^1.6.0",
2、运行环境：
浏览器：如谷歌浏览器/
vue版本：如vue@2.7.16
3、打包工具及版本：如webpack
问题描述：选择本地PDF文件预览,pdf文件打开显示空白
代码如下
`<template>
  <div class="about">
    <input type="file" @change="changeFile" />
    <div class="box-scale">
      <vue-office-pdf :src="pdfUrls" class="docx-calss" @rendered="rendered" @error="error" />
    </div>
  </div>
</template>

<script>
import VueOfficePdf from "@vue-office/pdf";
export default {
  name: 'pdfPreview2',
  data() {
    return {
      pdfUrls: "http://192.175.1.188:9000/test/test.pdf"
    };
  },
  components: {
    VueOfficePdf,
  },
  methods: {
    rendered() {
      console.log('ddddddddd');
    },
    error () {
      console.log('3eeeeeee');
    },
    changeFile(event) { //也可以预览本地上传的pdf文件
      let _this = this;
      console.log(event.target.files[0]);
      const reader = new FileReader();
      reader.addEventListener('load', function() {
        _this.pdfUrls = reader.result;
      })
      reader.readAsDataURL(event.target.files[0]);
    }
  },
}
</script>>

<style scoped>
.about {
  width: 800px;
  height: 400px;
  border: 1px solid red;
  overflow: auto;
}
.box-scale {
  transform: scale(0.8);
  transform-origin: center top; /*设置缩放中心点*/
  transition: .2s;
}
.docx-calss {
  height: 100%;
}
</style>`

**Comment by micro-carving** [comment]
我也遇到类似问题，只不过我是下载大佬源码下来直接用的examples目录下的静态文件进行预览，预览本地文件也是出现空白，但是预览大佬提供的test.pdf文件又是没问题的，我换了本地其他的PDF也显示空白。

**Comment by Xujalg** [comment]
有人解决这个吗？

**Comment by 501351981** [comment]
用新版本试试
