### ISSUE TITLE
IOS手机端—微信环境PDF无法预览

### ISSUE THREAD

**Issue by Alibaba-Jarry** [501351981/vue-office#209]
安卓手机可以预览PDF，苹果手机不行
微信版本：8.0.45
IOS系统：17.2.1
Node版本：v14.18.3
js-preview/pdf: "^1.6.0"
`
    import jsPreviewPdf from "@js-preview/pdf";
`
`
    const myPdfPreviewer = jsPreviewPdf.init(document.getElementById('pdf'));
`
`
    myPdfPreviewer.preview('http://192.168.50.142:8091/3333.pdf').then(res => {
      console.log('预览完成');
    }).catch(e=>{
      console.log('预览失败', e);
    })
`
苹果手机打开是灰色的，输出是预览成功
![image](https://github.com/501351981/vue-office/assets/34367661/f63a21b9-36f6-4249-98bd-172da468b036)

![image](https://github.com/501351981/vue-office/assets/34367661/b08716f8-e579-47c1-a935-764521f2c1c5)

**Comment by 501351981** [comment]
1.6.1版本可以吗

**Comment by lianglf-code** [comment]
问题还存在！

**Comment by lianglf-code** [comment]
大佬，1.6.1版本在苹果浏览器还是不能预览pdf的
![image](https://github.com/501351981/vue-office/assets/75355303/9ab9cdfe-6c35-44da-9d82-2904c464fddf)
![Snipaste_2024-01-24_17-48-10](https://github.com/501351981/vue-office/assets/75355303/35c96a43-82b0-4330-aa7f-8f8468ae5e15)

**Comment by lianglf-code** [comment]
大佬，1.6.1版本在苹果浏览器还是不能预览pdf的
![Uploading Snipaste_2024-01-24_17-48-10.jpg…]()

**Comment by lianglf-code** [comment]
大佬，1.6.1版本在苹果浏览器还是不能预览pdf的
![image](https://github.com/501351981/vue-office/assets/75355303/6cd18948-e6fa-4ad5-b248-4d5bb42061c2)

**Comment by 501351981** [comment]
用这个库试试呢？纯js预览 https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

**Comment by lianglf-code** [comment]
大佬，页面加载就报错了
![image](https://github.com/501351981/vue-office/assets/75355303/f2ca3429-9e0e-4ef7-870f-ad0c2e99bf87)

**Comment by 501351981** [comment]
哪个版本浏览器啊

**Comment by lianglf-code** [comment]
![image](https://github.com/501351981/vue-office/assets/75355303/be3b67a9-6b9f-4469-a0b8-9be203a947a6)

**Comment by 501351981** [comment]
不至于吧，看看代码怎么写的
