### ISSUE TITLE
pdf组件控制台报 window.pdfjsLib未找到

### ISSUE THREAD

**Issue by its-cool** [501351981/vue-office#210]
pdf 1.6.0版本window.pdfjsLib错误警告

**Comment by its-cool** [comment]
vue 2.6.11
node 14.18.0
googelChrome
pdf   1.6.0

项目中使用pdf组件 无法打开pdf  控制台显示  window.pdfjsLib 未找到

**Comment by dh336699** [comment]
同问, 问题有解决么

**Comment by I-love-learn** [comment]
使用微前端了吗？

**Comment by I-love-learn** [comment]
我也遇到了  但我是微前端  对window进行了一个属性劫持就好了

**Comment by xietao91** [comment]
> 我也遇到了 但我是微前端 对window进行了一个属性劫持就好了

怎么劫持的呀，我劫持属性一直报栈溢出错误

**Comment by I-love-learn** [comment]
> > 我也遇到了 但我是微前端 对window进行了一个属性劫持就好了
> 
> 怎么劫持的呀，我劫持属性一直报栈溢出错误

你是微前端吗，我用的无界  在插件那个地方加这么一段代码
`jsBeforeLoaders: [
      {
        callback(appWindow) {
          console.log(appWindow)
          // 后续若有其他属性需要修正，只需在这里添加需要重写的属性即可
          const propsNeedAdjust = 'pdfjsLib'

          Object.defineProperty(appWindow, propsNeedAdjust, {
            get: function () {
              if (appWindow.__POWERED_BY_WUJIE__) {
                return appWindow.parent[propsNeedAdjust]
              } else {
                // 返回原始值
                return appWindow[propsNeedAdjust]
              }
            }
          })
        }
      }
    ]`
