### ISSUE TITLE
excel预览时，有些文件会在前面加两个未知的页签

### ISSUE THREAD

**Issue by TongKaiQiang** [501351981/vue-office#215]
1、组件名称及版本：@vue-office/excel@1.6.0

2、运行环境：chrome @120.0.6099.131  、vue@2.7.16 

3、问题描述：excel预览时，有些文件会在前面加两个未知的空白页签，源文件没有这两个页签，如下图：
插件预览：
![f7515e1501c9b888498562a30c4164db](https://github.com/501351981/vue-office/assets/12757040/01dac125-b599-48fb-a62a-8c3ffe239a05)

源文件office软件打开：
![image](https://github.com/501351981/vue-office/assets/12757040/f86739e8-05bc-4b30-8360-e075549ce2d6)

**Comment by 501351981** [comment]
上传个示例文件吧，我有时间试试

**Comment by TongKaiQiang** [comment]
@501351981 
打印的workbookData里面：
![image](https://github.com/501351981/vue-office/assets/12757040/ba942a44-b945-4ba0-92f5-3338bd3a7218)

**Comment by 501351981** [comment]
打印有，就说明是有过，不清楚这个文件经历了什么
