### ISSUE TITLE
excel在移动端(iOS & android)预览会弹出键盘

### ISSUE THREAD

**Issue by wangweiqing1986** [501351981/vue-office#22]
excel在移动端预览时，点击底部tab切换sheet时会弹出键盘

**Comment by 501351981** [comment]
收到，已复现，抽空处理

**Comment by wangweiqing1986** [comment]
补充一下：在sheet上点击一下，然后开始上下滑动也会弹出键盘

**Comment by 501351981** [comment]
试试最新版本： @vue-office/excel@0.2.7

**Comment by wangweiqing1986** [comment]
键盘不会弹出了，但是切换sheet页面会放大，双击屏幕才能变回原来大小

**Comment by 501351981** [comment]
修改你的html中的header，禁止页面放大
 <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />

**Comment by 501351981** [comment]
` <meta name="viewport"
          content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />`

**Comment by iyanming** [comment]
安卓手机还是会弹出键盘 @501351981

**Comment by iyanming** [comment]
"@vue-office/excel": "^1.4.2",

**Comment by Boo-PiG** [comment]
"@vue-office/excel": "^1.4.5"     ios和安卓滑动都会弹出键盘

**Comment by AdstorLin** [comment]
> "@vue-office/excel": "^1.4.5" ios和安卓滑动都会弹出键盘

我在渲染结束后 遍历整个界面的input和textarea属性设置为readonly就不会弹出了

**Comment by Boo-PiG** [comment]
> > "@vue-office/excel": "^1.4.5" ios和安卓滑动都会弹出键盘
> 
> 我在渲染结束后 遍历整个界面的input和textarea属性设置为readonly就不会弹出了

我也是这么处理的，我还加了一行document.activeElement.blur();
