### ISSUE TITLE
uniapp 中引用运行异常

### ISSUE THREAD

**Issue by alsdn123123** [501351981/vue-office#221]
![QQ截图20240129163009](https://github.com/501351981/vue-office/assets/38528755/7c20cff8-d6b2-4016-b5ec-bb4079fde333)
![Uploading QQ截图20240129163111.jpg…]()

**Comment by 501351981** [comment]
那查找失败的文件到底存在不存在呢？

**Comment by alsdn123123** [comment]
> 那查找失败的文件到底存在不存在呢？

文件是存在的，不过用非vue那个没问题了。
