### ISSUE TITLE
自己的pdf 无法访问 但demo 的test 可以

### ISSUE THREAD

**Issue by Xujalg** [501351981/vue-office#222]
1、组件名称及版本：@js-preview/pdf@1.6.1

2、运行环境：chrome @120.0.6099.131 、react^16.8.6

3、问题描述：我自己的pdf 无法展示  日志是预览成功 但一直是空白 
然后 说明文档里面 http://static.shanhuxueyuan.com/test.pdf  也是空白
说明文档的 https://501351981.github.io/vue-office/examples/dist/static/test-files/test.pdf  这个是可以展示的

**Comment by RayChou0122** [comment]
我也出现了这个问题
windows11 Microsoft Edge版本 121.0.2277.83 (正式版本) (64 位)，搜狗浏览器11.0.1.34700 
两个浏览器效果一致

- vue2.6.10
- vue-office/pdf 1.6.1
- vue-demi: 0.14.6
- vue/composition-api: 1.7.2 
 
示例的test.pdf可以正常渲染，除此之外测了大概十几个pdf，包括从网上下载的，自己wps导出的，typora导出的，都只能渲染出页数和比例正确的空白页。只有个别正常渲染。

成功的：
- [2023级研究生新生入学教育须知.pdf](https://github.com/501351981/vue-office/files/14105936/2023.pdf)

空白的:
- [计算理论题目收集.pdf](https://github.com/501351981/vue-office/files/14105963/default.pdf)
- [2023-2024年第二学期课表_0115.pdf](https://github.com/501351981/vue-office/files/14105940/2023-2024._0115.pdf)
- 测试的很大部分都是空白的

只渲染了几页:
- 关于书的pdf只渲染了5页，但文件太大了，传不上来，我也不记得在哪下的了 Java设计模式 (刘伟) (Z-Library).pdf
- 还有一本也太大了，传不上来，也只渲染了4页：需求工程  软件建模与分析  第2版_骆斌主编；丁二玉编著.pdf

渲染错误的:
- [カタオモイ-Aimer.pdf](https://github.com/501351981/vue-office/files/14105974/-Aimer.pdf)

**Comment by heeryuy** [comment]
我测试下来是因为pdf里带了base64格式的图片导致的

**Comment by Xujalg** [comment]
你解决了吗？  看源码 好像是pdf.js 的问题 

> 我测试下来是因为pdf里带了base64格式的图片导致的

**Comment by heeryuy** [comment]
> 你解决了吗？ 看源码 好像是pdf.js 的问题
> 
> > 我测试下来是因为pdf里带了base64格式的图片导致的

我换成直接调用pdfjs可以正常预览了

**Comment by Xujalg** [comment]
> > 你解决了吗？ 看源码 好像是pdf.js 的问题
> > > 我测试下来是因为pdf里带了base64格式的图片导致的
> 
> 我换成直接调用pdfjs可以正常预览了

好的 那我也用pdf.js 预览pdf

**Comment by 501351981** [comment]
可以试试新版本， 1.6.2

**Comment by Xujalg** [comment]
> 可以试试新版本， 1.6.2

好 我试一下
