### ISSUE TITLE
电脑端可以了，手机端就失败

### ISSUE THREAD

**Issue by 851605063** [501351981/vue-office#223]
我打印了一下错误
渲染失败 
t {message: "Failed to fetch", name: "UnknownErrorException", details: "TypeError: Failed to fetch"}
details: "TypeError: Failed to fetch"
message: "Failed to fetch"
name: "UnknownErrorException"
[[Prototype]]: Object

**Comment by 851605063** [comment]
使用pdf组件的时候

**Comment by 851605063** [comment]
组件名称及版本：     "@vue-office/pdf": "^1.6.1
运行环境：安卓微信
浏览器：安卓微信
vue版本：vue@3.2.24
打包工具及版本：vite@5.0.0
代码如下：
<template>
    <div style="height: 100vh;width: 100vw;overflow: auto">
        <vue-office-pdf
            :src="pdf"
            @rendered="renderedHandler"
            @error="errorHandler"
        />






    </div>

</template>

<script>
//引入VueOfficePdf组件
import VueOfficePdf from '@vue-office/pdf'
import VueOfficeDocx from "@vue-office/docx";

export default {
    components: {
        VueOfficePdf,
        VueOfficeDocx
    },
    data() {
        return {
            // pdf: 'http://static.shanhuxueyuan.com/test.pdf' //设置文档地址
            pdf: 'https://dk.qfgk.top/pdf/md.pdf' ,//设置文档地址
            // docx: 'http://127.0.0.1:8202/pdf/1.docx' //设置文档网络地址，可以是相对地址
        }
    },
    methods: {
        renderedHandler() {
            console.log("渲染完成")
        },
        errorHandler(e) {
            console.log("渲染失败",e)
        }
    }
}
</script>


问题：我试了电脑端的谷歌浏览器，edge浏览器还有微信开发者工具都可以展示，但是真机上就报错

**Comment by caoshengshi** [comment]
> 使用pdf组件的时候

大佬，问题解决了吗？同样的问题，@vue-office/pdf在移动端预览PDF显示空白，目前是使用vue-pdf作为临时解决方案，不过这个项目大概两三年没有维护了，还存在BUG。

**Comment by 501351981** [comment]
你们是怎么使用的，在UniAPP里面？

**Comment by caoshengshi** [comment]
> 你们是怎么使用的，在UniAPP里面？

升级了一下版本，移动端不显示的问题已经解决了@vue-office/pdf version=1.6.2，有问题的版本是1.6.0

**Comment by 501351981** [comment]
好的

**Comment by 851605063** [comment]
> pdf

我用别的了，vue-pdf-app，我感觉比这个好用
