### ISSUE TITLE
升级到1.6.1预览PDF发票缺少边框

### ISSUE THREAD

**Issue by KaneLeung** [501351981/vue-office#224]
1.组件名称及版本： 如@vue-office/pdf@1.6.1
运行环境：
浏览器：如EDGE浏览器
vue版本：vue@3.4.15
打包工具及版本：vite@5.0.12
问题描述：升级到1.6.1预览PDF发票缺少边框，退回1.6.0则恢复正常

![image](https://github.com/501351981/vue-office/assets/24695053/612c94d3-0e62-436f-b8b6-6926635fb949)
这是1.6.0版本预览效果

![image](https://github.com/501351981/vue-office/assets/24695053/a2da5bc1-aeeb-4207-89cd-7b94a100ca1d)
这是1.6.1版本预览效果

**Comment by 501351981** [comment]
已处理 1.6.2
