### ISSUE TITLE
Tdesign next - isFunction is not a function

### ISSUE THREAD

**Issue by engriary** [501351981/vue-office#225]
组件名称及版本： "@vue-office/docx": "^1.6.0"
运行环境：'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
浏览器：谷歌浏览器
vue版本："vue": "^3.3.13"
打包工具及版本："vite": "^4.5.0"
问题描述：vue 提示 isFunction is not a function 报错
![image](https://github.com/501351981/vue-office/assets/20064659/aa68ed81-bd3b-47c5-bda2-618377841da0)

重现步骤：
1.安装项目&依赖 https://tdesign.tencent.com/starter/docs/vue-next/get-started
npm i tdesign-starter-cli -g
td-starter init
npm install

2.添加vue-office组件
npm i vue-office --save

3.组件使用
![image](https://github.com/501351981/vue-office/assets/20064659/caab6e16-b31c-4331-b0d0-506436558b73)

4.运行启动命令，整个项目白屏，报isFunction is not a function

**Comment by 501351981** [comment]
有问题的都换纯js预览方式吧，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

**Comment by engriary** [comment]
纯js预览方式可行，谢谢
