### ISSUE TITLE
PDF预览没有效果，浏览器控制台报错  docx  excel预览都是正常的

### ISSUE THREAD

**Issue by ccqaiqd** [501351981/vue-office#227]
1 . 组件名称及版本： @vue-office/pdf@1.2.0
2. 运行环境：
    谷歌浏览器： 83.0.4103.106   
    vue版本：vue@2.6.10
    打包工具及版本：webpack@4.6.0
3.问题描述：
    在预览pdf时浏览器控制台报如下错误
    Uncaught (in promise) Typeerror: Cannot read property 'GlobalWorkerOptions' of undefined at eval (index.js?a147:1)

**Comment by 501351981** [comment]
是不是用了其他pdf预览组件，有冲突吧，如vue-pdf之类的

**Comment by ccqaiqd** [comment]
解决了   pdf/lib/index.js 这个文件的问题  换个版本就解决了   @vue-office/pdf 1.5.5的就正常   1.2.0的就会报错GlobalWorkerOptions  希望后面其他人遇到这个问题换 1.5.5  我暂时是这么解决的
