### ISSUE TITLE
如何像演示demo一样获取excel工作簿数据呢？

### ISSUE THREAD

**Issue by wenxin1114** [501351981/vue-office#228]
我需要获取那些内容
![2a78c970a3783c47ab26e5af9bf44640](https://github.com/501351981/vue-office/assets/64764312/faf38cc6-5b2f-49a7-bd1c-a74c21fc421a)

**Comment by 501351981** [comment]
https://501351981.github.io/vue-office/examples/docs/config/
<img width="839" alt="image" src="https://github.com/501351981/vue-office/assets/14229082/6351fb01-1a0d-417f-a0e3-fef867bdd69d">
