### ISSUE TITLE
vue2+ant-design  使用office无效

### ISSUE THREAD

**Issue by CaoUncle** [501351981/vue-office#23]
组件名称及版本： 如@vue-office/docx@0.2.2
运行环境：
浏览器：谷歌浏览器
vue版本：@vue/cli 5.0.8
打包工具及版本：vue-cli
问题描述：
引入后 使用没效果
![image](https://user-images.githubusercontent.com/47659300/226568119-1c6e43fa-40ad-4992-83fe-f75e7d5c5ff3.png)
![image](https://user-images.githubusercontent.com/47659300/226568209-52bf20ca-b7e3-424d-a0e0-bc2e0b0bd8d5.png)
src是内网搭建的minio文件服务器上传后的url

**Comment by 501351981** [comment]
可能两个问题，第一是检查下是否存在跨域问题，第二只支持docs文件，不支持doc，如何都不是可以把文件传给我看看，微信\_hit757_

**Comment by CaoUncle** [comment]
谢谢大佬
