### ISSUE TITLE
vue-office-excel 第一次查看文件的图片，在第二次空文件出现，

### ISSUE THREAD

**Issue by reticency** [501351981/vue-office#234]
![1708667461265](https://github.com/501351981/vue-office/assets/129018897/592f7d05-80fb-4854-af60-cec9482a0c1f)
![1708667493201](https://github.com/501351981/vue-office/assets/129018897/743ef87b-f701-45ed-b285-67e15098ef28)

**Comment by 501351981** [comment]
如何复现的？详细步骤有吗

**Comment by reticency** [comment]
<vue-office-excel
            :src="showData.excelFileSrc"
            style="height: 100vh;"
           />
是 list 以轮播的方式进行，list 有部分 excelFileSrc 是没有内容的，有部分有内容，没有内容的部分也显示出来之前的图片了。

**Comment by reticency** [comment]
`<vue-office-excel
            :src="showData.excelFileSrc"
            style="height: 100vh;"
           />`

**Comment by 501351981** [comment]
1.6.4

**Comment by reticency** [comment]
更新到 1.6.4 还是不行哦，

**Comment by reticency** [comment]
![image](https://github.com/501351981/vue-office/assets/129018897/facc92b9-f8af-4737-86b2-3cf70736078c)

**Comment by 501351981** [comment]
那试试1.6.5吧，如果还不行，需要详细描述下问题了，我好精确判断下有问题的地方
