### ISSUE TITLE
TransformData options for js-preview-excel

### ISSUE THREAD

**Issue by Cirmiir** [501351981/vue-office#235]
1.  js-preview/excel

Hello,
Thanks a lot for the useful library. if it is possible could you please help with one question.
The js-preview/excel version doesn't support the transformData and this option is quite useful to manipulate the data before display it.

I checked locally the potentially changes and it looks like the changes are not big. 
Could you please advise if there is any additioanl issues with this functionality for js-preview/excel?

If this changes can be useful for library and won't  cause any issues with other works. If there are no issues, I will be happy to help with this and prepare PR.

Thanks a lot.

**Comment by 501351981** [comment]
好的，我看下

**Comment by 501351981** [comment]
试试这个版本，@js-preview/excel@1.6.2

By the way, which country are you from？
