### ISSUE TITLE
有个bug很烦阿

### ISSUE THREAD

**Issue by FuLei-hub** [501351981/vue-office#237]
docx里的:requestOptions是正常的，pdf里就不行，自定义任何请求头都发不了，很坑阿，最新版

**Comment by 501351981** [comment]
我知道你很烦，但是你先别烦，我这不也是免费给大家服务嘛~~

已更新：1.6.3版本

**Comment by FuLei-hub** [comment]
> 我知道你很烦，但是你先别烦，我这不也是免费给大家服务嘛~~
> 
> 已更新：1.6.3版本

老板666，英雄声名在外，钱财身外之物，祝老板发财
