### ISSUE TITLE
组件不支持 node v16.20.2  这版本

### ISSUE THREAD

**Issue by yaLingzh** [501351981/vue-office#240]
Failed to resolve entry for package "@vue-office/docx". The package may have incorrect main/module/exports specified in its package.json.

在node 版本 v16.20.2， npm  版本 9.5.1 里报以上的错误

**Comment by 501351981** [comment]
那就检查下包中package.json内的main中指定的文件存在不存在

**Comment by 501351981** [comment]
和node没关系，检查下包是否安装成功；看看你的打包工具及引入相关代码
