### ISSUE TITLE
excel xlsx格式文件图片有时候预览不出来

### ISSUE THREAD

**Issue by loveyyao** [501351981/vue-office#252]
![image](https://github.com/501351981/vue-office/assets/45845997/dfd61c93-2f8f-42ba-b716-bd238c076d47)
[karingbee咖啡机选品竞品分析3.22(2).xlsx](https://github.com/501351981/vue-office/files/14692723/karingbee.3.22.2.xlsx)

在这份文件里，图片是预览不出来的，我这边打断点查看了一下，`renderImage`方法里调用的`calcPosition`方法返回的`width`、`height`都是`NAN`。这个问题大佬看看能修复一下吗

**Comment by 501351981** [comment]
1.7.2
不用谢，要谢就给作者打赏请喝杯奶茶，哈哈

**Comment by loveyyao** [comment]
![image](https://github.com/501351981/vue-office/assets/45845997/e868cb0a-a3a6-4c7c-b199-6160df2a14ab)
第三个sheet页下面有个图片被压缩了呢，大佬 ╥﹏╥

**Comment by loveyyao** [comment]
> 1.7.2 不用谢，要谢就给作者打赏请喝杯奶茶，哈哈

以打赏，大佬再帮看看这个吧，救救孩子╥﹏╥
