### ISSUE TITLE
解析不了xls格式的excel

### ISSUE THREAD

**Issue by Mophar-gift** [501351981/vue-office#255]
# 使用.xls格式文件时，解析报警告

## 版本及运行环境：
- "@vue-office/excel": "^1.7.2"
- "vue": "^3.4.21"
- "vite": "^5.2.2"

## 预览环境：
- 谷歌浏览器

## 警告截图：
![image](https://github.com/501351981/vue-office/assets/67857649/4919b43a-4bcb-444e-8e93-0adcc8c1630e)

**Comment by 501351981** [comment]
看文档

**Comment by Mophar-gift** [comment]
> 看文档

## 看了文档发现文档里说的是不支持xls文件，但是在您提供的demo预览里发现却可以，还是说我的使用方式出了问题
![image](https://github.com/501351981/vue-office/assets/67857649/cc0c7bbd-ed6b-4ad5-9038-80964d1e0d0d)

**Comment by 501351981** [comment]
https://501351981.github.io/vue-office/examples/docs/guide/preview-xlsx.html

**Comment by 501351981** [comment]
最近刚支持的
