### ISSUE TITLE
Error: Dynamic require of "vue-demi" is not supported

### ISSUE THREAD

**Issue by cmtiger** [501351981/vue-office#256]
报如下错误：Error: Dynamic require of "vue-demi" is not supported
    at chunk-DYHMHIES.js?v=a4f0152a:29:9
    at index.js:1:89
    at node_modules/.pnpm/registry.npmmirror.com+@vue-office+docx@1.6.0_vue-demi@0.14.7_vue@3.2.33/node_modules/@vue-office/docx/lib/index.js (index.js:1:292)
    at __require2 (chunk-DYHMHIES.js?v=a4f0152a:35:50)
    at dep:@vue-office_docx:1:16
人工智能回答：
这个错误提示再次强调了在模块中动态 require() "vue-demi" 不被支持的问题，尤其是在Vite、Rollup或Webpack这类现代打包工具中。在这种情况下，@vue-office/docx 库似乎在内部使用了动态 require() 语句来导入 vue-demi。解决这个问题的步骤如下：1. 检查库版本： 首先，确认你所使用的 @vue-office/docx 版本是否是最新的。有时候，库的最新版本可能已经修复了这个问题。你可以查看库的GitHub仓库或npm页面，查找有关动态导入 vue-demi 的问题和更新记录。2. 提交Issue或寻求帮助： 如果当前版本仍然存在这个问题，可以去 @vue-office/docx 的GitHub仓库提交一个Issue，描述你遇到的问题，请求库的作者更新代码以支持静态导入 vue-demi。3. 临时解决方案： 作为一个临时解决方案，如果你有能力的话，可以尝试 fork @vue-office/docx 库并修改其源码，将动态导入 vue-demi 的地方改为静态导入。但这不是一个长期的解决方案，每次库更新都需要手动同步更改。4. 寻找替代库： 如果问题无法通过更新库得到解决，你可能需要寻找一个不依赖动态导入 vue-demi 的类似功能的库。总的来说，最好的解决办法是库作者能够修复这个问题，所以在他们的GitHub仓库提交Issue是很重要的一步。同时，你也应该密切关注库的更新情况，以便及时更新到修复问题的版本。

**Comment by 501351981** [comment]
纯js预览吧，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html
