### ISSUE TITLE
excel预览时，字体偏小，而且单元格没有边框是什么问题？ 样式如何调整？

### ISSUE THREAD

**Issue by wangshuo1991** [501351981/vue-office#258]
excel预览时，字体偏小，而且单元格有的有边框，有的没有边框，但是原来的excel就有边框，字体也很舒服，请问这是什么问题？ 样式如何调整？

vue-office渲染效果如下：
![Dingtalk_20240327112533](https://github.com/501351981/vue-office/assets/19642555/474876c3-78c3-4edd-b3e4-fa1d6524a17a)

**Comment by 501351981** [comment]
那你看看excel上面是几号字

**Comment by 501351981** [comment]
先看看源文件几号字，然后看看现在是多大，excel里面不能说放大了看，不缩放你的excel文件，看看一样大小不

**Comment by wangshuo1991** [comment]
> 先看看源文件几号字，然后看看现在是多大，excel里面不能说放大了看，不缩放你的excel文件，看看一样大小不

源文件倒是显示正常。
我现在通过 transformData 方法，重置了部分样式，先解决了这个问题。

**Comment by 501351981** [comment]
好，也是个办法，我测试时候看着大小还算已知，9号、10号字确实小，本来就小一些

**Comment by Mrmore** [comment]
@wangshuo1991  我也改了一个  发你邮箱里了
