### ISSUE TITLE
@vue-office/docx vue-demi@0.14.6预览空白，浏览器报错

### ISSUE THREAD

**Issue by hardgit** [501351981/vue-office#259]
版本：@vue-office/docx vue-demi@0.14.6
浏览器：Google
vue: ^3.2.25
vite:"^2.9.9

使用方法：
` 
<el-dialog v-model="dialogVisible2" title="预览">
<vue-office-docx 
            src="https://501351981.github.io/vue-office/examples/dist/static/test-files/test.docx" style="height: 70vh;"/>
  </el-dialog>
`
预览空白，浏览览器报错：
![image](https://github.com/501351981/vue-office/assets/31436497/d0d3bd9b-7d10-4880-983e-893e0a4a1236)

您好，是我使用的方式不对吗？浏览器一直报错……

**Comment by 501351981** [comment]
项目是用什么工具创建的，不行用纯js方式吧，https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

**Comment by 501351981** [comment]
是不是vite版本太低了，或者vue3版本太低了， 我用vite创建的测试项目没有问题，无法复现

**Comment by hardgit** [comment]
嗯，就是因为vite版本太低了
