### ISSUE TITLE
在EXCEL中多个cell，fill相同颜色后，会连在一片。但网页中显示却是白线分隔的

### ISSUE THREAD

**Issue by hyfbeetle** [501351981/vue-office#26]
非常不错！首先给作者点赞！
一开始以为是 x-spreadsheet  .container * {box-sizing: content-box}  样式问题，试了不是。
cell 的border也要赋相同颜色也没解决。
这间隙不知道是啥?

**Comment by 501351981** [comment]
看了半天，暂时无法解决

**Comment by hyfbeetle** [comment]
https://github.com/wolf-table/table   作者已经解决了，可以考虑换了
