### ISSUE TITLE
pdf浏览13M文件 浏览器内存溢出

### ISSUE THREAD

**Issue by zr12041019** [501351981/vue-office#263]
【版本】 @js-preview/pdf 1.6.5
【问题】浏览13M的文件  浏览器内存溢出
是否有开启懒加载的功能？

**Comment by zr12041019** [comment]
运行环境 ：
node 14.21.3
vue 3.3.4
@vue/cli  webpack 4.47.0

**Comment by 501351981** [comment]
已解决 版本 2.0.1
