### ISSUE TITLE
vue3使用VueOfficeExcel报错

### ISSUE THREAD

**Issue by wangstar615** [501351981/vue-office#265]
![image](https://github.com/501351981/vue-office/assets/83524770/7d257518-4ab6-43d8-854a-70089ff4c0c6)

"@vue-office/excel": "^1.7.0",
"vue": "^3.2.25",
"vite": "^3.0.1",

 <vue-office-excel
        :src="excel"
        style="height: 100vh"
        @rendered="renderedHandler"
        @error="errorHandler"
 />
 
const res = await getFile... （responseType: 'blob',）

 res.arrayBuffer().then(file => {
        excel.value = file;
      });

报错无法展示内容

![image](https://github.com/501351981/vue-office/assets/83524770/b349b099-9309-41ae-b0ab-8a89bdf3fc17)

**Comment by 501351981** [comment]
1. 可能vite版本太低，升级vite版本到最新
2. 如果不想升级可以换纯js预览：https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

**Comment by wangstar615** [comment]
> 1. 可能vite版本太低，升级vite版本到最新
> 2. 如果不想升级可以换纯js预览：https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

升级vite版本到最新后可以展示出来了，感谢

**Comment by wangstar615** [comment]
> 1. 可能vite版本太低，升级vite版本到最新
> 2. 如果不想升级可以换纯js预览：https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html

大佬 可以预览csv格式的文件吗？

**Comment by 501351981** [comment]
目前不支持csv
