### ISSUE TITLE
js-preview/excel字体会模糊

### ISSUE THREAD

**Issue by a987607481** [501351981/vue-office#268]
![1713348462473](https://github.com/501351981/vue-office/assets/52713259/2657fe11-2052-490c-aa67-10feabd48575)

**Comment by 501351981** [comment]
上传下文件看看

**Comment by a987607481** [comment]
[策略入库证券信息列表模板.xlsx](https://github.com/501351981/vue-office/files/15023845/default.xlsx)

**Comment by a987607481** [comment]
> 上传下文件看看

[证券入库查询列表.xlsx](https://github.com/501351981/vue-office/files/15023863/default.xlsx)
有可能是字体大小的原因，我把字体大小改掉就正常了

**Comment by a987607481** [comment]
> 上传下文件看看

[测试数据.xlsx](https://github.com/501351981/vue-office/files/15023885/default.xlsx)
有可能是字体大小的原因，我把字体size删了就正常了
