### ISSUE TITLE
PDF显示不全,只显示了一半

### ISSUE THREAD

**Issue by Zqc925** [501351981/vue-office#269]
![image](https://github.com/501351981/vue-office/assets/105917129/66590113-5afa-464c-b219-6ebe443896fa)
我预览的一张发票,第二页有很长的清单共10条,无法显示全.我在你的demo里也上传该文件了,一样显示不全.

**Comment by Zqc925** [comment]
还有就是`
 const VueOfficePdf: {
    install?: (vue: any) => void;
    src: string|ArrayBuffer|Blob;
    rerender?: () => any;
    staticFileUrl?: string,
    requestOptions?: any;
    options?: any
};`这个options能配置些什么,文档中没有,翻阅issues看见好像有个lazy属性,还有其他的属性吗?

**Comment by 501351981** [comment]
文件发下，记得设置组件的高度

**Comment by Zqc925** [comment]
[invoice2.pdf](https://github.com/501351981/vue-office/files/15041523/invoice2.pdf)
设置了的

**Comment by 501351981** [comment]
先用 1.6.5 版本吧

**Comment by Zqc925** [comment]
好的

**Comment by raobinhui** [comment]
> 已修复，版本：2.0.2

2.0.2版本还是会显示不全只能显示 5 页1.6.5版本可以

**Comment by tyn520215** [comment]
> 已修复，版本：2.0.2
还是会显示不全
