### ISSUE TITLE
excel文件预览空白

### ISSUE THREAD

**Issue by ixaseu** [501351981/vue-office#270]
版本：
"vue": "^3.4.21",
 "vite": "^5.2.8",
"@vue-office/excel": "^1.7.6",
![image](https://github.com/501351981/vue-office/assets/51012949/f4dcbfc2-67c6-4f4c-b9d2-6e08876b599d)
![image](https://github.com/501351981/vue-office/assets/51012949/06bc9440-8b9d-4a4a-aaf5-60af50f4bfb9)

**Comment by 501351981** [comment]
是不是用了mockjs之类的，关闭看看

**Comment by ixaseu** [comment]
> 是不是用了mockjs之类的，关闭看看

感谢，已解决，确实是这个问题
