### ISSUE TITLE
globalThis is not defined

### ISSUE THREAD

**Issue by chengbieSWL** [501351981/vue-office#273]
组件名称及版本：
    "@vue-office/docx": "^1.6.0",
    "@vue-office/excel": "^1.7.6",
    "@vue-office/pdf": "^2.0.1",
运行环境：
浏览器：浏览器
vue版本："vue": "3.2.45"
打包工具及版本："vite": "3.2.3"
问题描述：globalThis is not defined
   浏览器无法提供版本，应该是个国产浏览器，没见过，涉密，支持vue3，
   我在项目中使用了这三个库，然后报错  globalThis is not defined，
   我看到代码中有些地方判断了globalThis != "undefined"，
   有些地方则没有判断，直接使用了，如  typeof globalThis === "object" , 好像是excel库，
   不知道我是否排查正确

**Comment by 501351981** [comment]
自行配置
if(!window.globalThis){
  window.globalThis = window
}
