### ISSUE TITLE
excel只能渲染半页数据

### ISSUE THREAD

**Issue by xiaoniu666888** [501351981/vue-office#276]
请问excel只能渲染半页数据是什么情况呢，是我的代码有问题吗
![image](https://github.com/501351981/vue-office/assets/107358468/786de9bd-1754-4445-b06b-d1ad51baf5b1)

![image](https://github.com/501351981/vue-office/assets/107358468/787ecc2e-e2c9-46e0-9a4d-6cd8e2ceac07)

**Comment by 501351981** [comment]
在官网示例下试试，https://501351981.github.io/vue-office/examples/dist/#/excel

**Comment by xiaoniu666888** [comment]
官网上传没问题，是我样式配置错了吗

**Comment by xiaoniu666888** [comment]
然后我这里渲染出来的好像和官网也不太一样，我这里的表格不能选复制，官网可以

**Comment by 501351981** [comment]
没引用css文件吧
