### ISSUE TITLE
VueOfficePdf不展示

### ISSUE THREAD

**Issue by yeahjsen** [501351981/vue-office#28]
测试机： SE， oppo

SyntaxError: Invalid character: '#'\n\tdata:text/javascript;base64,IWZ1bmN0aW9uIHdlYnBhY2tVbml2ZXJzYWxNb2R1bGVEZWZpbml0aW9uKHQsZSl7Im9iamVjdCI9PXR5cGVvZiBleHBvcnR...

Uncaught (in promise)  {"name": "TypeError", "message": "undefined is not an object (evaluating 'window.pdfjsLib.GlobalWorkerOptions')"

**Comment by 501351981** [comment]
已解决，@vue-office/pdf@0.2.5
如果好了麻烦给项目点个赞，感谢

**Comment by Kidxiangxiang** [comment]
vue项目 vite打包，后报错
ReferenceError: Cannot access 'e' before initialization
    at @vue-office-CaMZld44.js:1:2062556
    vue版本3.4.21，vite版本5.2.0

**Comment by dai-yi-heng** [comment]
> vue项目 vite打包，后报错 ReferenceError: Cannot access 'e' before initialization at @vue-office-CaMZld44.js:1:2062556 vue版本3.4.21，vite版本5.2.0

你好，我也遇到了，请问解决了吗
