### ISSUE TITLE
excel文件识别有误显示空白

### ISSUE THREAD

**Issue by javachens** [501351981/vue-office#281]
组件加载Excel文件时候识别不了xls文件，加载不了数据
组件名称及版本：    "@vue-office/excel": "^1.7.8",
运行环境：
浏览器：谷歌浏览器
vue版本："vue": "^3.3.8",
打包工具及版本："vite": "4.5.0",
@vue-office_excel.js?v=7bc1c683:47432 Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    at c3.readEndOfCentral (@vue-office_excel.js?v=7bc1c683:23482:137)
    at c3.load (@vue-office_excel.js?v=7bc1c683:23502:48)
    at @vue-office_excel.js?v=7bc1c683:22752:31

**Comment by 501351981** [comment]
预览xls文件需要配置属性 :options="{xls: true}"
