### ISSUE TITLE
源码为什么不放出来？

### ISSUE THREAD

**Issue by cordmaker** [501351981/vue-office#283]
研究了一上午编译后的代码，发现 docx 预览用的 docx-preview，xlsx 预览用的 exceljs，pdf 预览用的 pdfjs，全是开源库，只是在做封装而已，看源码还要打赏，哥们你疯了吧

**Comment by liuwenlong916** [comment]
哈哈哈，盖了帽了

**Comment by 501351981** [comment]
那你自己写就是了

**Comment by 501351981** [comment]
第一：影响你用了吗？不是免费给大家用的吗？
第二：开源了你会贡献代码还是能有啥帮助？
第三：没人欠你的，那你也可以自己封装下免费开源
