### ISSUE TITLE
预览Excel时，表格宽度有问题，Uncaught TypeError: Cannot read properties of null (reading 'clientWidth')

### ISSUE THREAD

**Issue by sos233** [501351981/vue-office#29]
1、组件名称及版本：
@vue-office/excel@0.2.10
ant-design-vue@1.6.5

2、运行环境：
浏览器：谷歌浏览器 111.0.5563.65
vue版本：vue@2.7.14
打包工具及版本：webpack@4.44.2

3、问题描述：（如果有报错，麻烦粘贴详细的报错信息、package.json内容等）

`  <a-modal dialogClass="file-modal" v-model="modelVisible" width="900px" :footer="null" @cancel="handleClose"
           destroyOnClose>
    <vue-office-excel :src="file.url" style="height:70vh;width:100%;" @rendered="renderedHandler"
                      @error="errorHandler" />
  </a-modal>`

你好，我用a-modal做了一个弹窗预览excel，首次打开是宽度是正常的
![image](https://user-images.githubusercontent.com/7446920/230716144-c800df30-c0e7-498f-a8dc-98c4e9b069a1.png)
关闭后再次打开，宽度就有问题了
![image](https://user-images.githubusercontent.com/7446920/230716159-e517ab80-20c2-4cbd-bffd-529206ba81d7.png)

F12打开后，有如下报错信息

Uncaught TypeError: Cannot read properties of null (reading 'clientWidth')
    at Object.width (index.js?b690:99:1)
    at sh.viewWidth (index.js?b690:4:1)
    at rp.getRect (index.js?b690:14:1)
    at rp.getTableOffset (index.js?b690:14:1)
    at rp.sn (index.js?b690:14:1)
    at rp.reload (index.js?b690:14:1)
    at eval (index.js?b690:14:1)

麻烦看一下是什么问题

**Comment by 501351981** [comment]
在弹窗展示后加个延迟，然后再显示预览组件，可能是弹窗展示期间弹窗dom宽度没有获取到

**Comment by sos233** [comment]
> 在弹窗展示后加个延迟，然后再显示预览组件，可能是弹窗展示期间弹窗dom宽度没有获取到

多谢，加了个nextTick后，现在可以了
