### ISSUE TITLE
vue2安装excel报错

### ISSUE THREAD

**Issue by lineys** [501351981/vue-office#3]
ERROR  Failed to compile with 1 errors                                                                                                                                       下午6:39:46

 error  in ./node_modules/@vue-office/excel/lib/index.js

Module parse failed: Unexpected token (44:181977)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

**Comment by 501351981** [comment]
在多个vue2环境下试验没有复现这个问题，如果方便的话可以把代码发我看看，可以把无关业务代码都去掉，只给一个最小的验证环境，我的微信号：_hit757_

**Comment by 501351981** [comment]
已解决，可下载最新版本即可
