### ISSUE TITLE
Vue 3.4.29 下 npm install @vue-office/docx vue-demi 报错

### ISSUE THREAD

**Issue by HappyQuQu** [501351981/vue-office#304]
Vue 3.4.29 下安装提示依赖错误

Vue 3.2.45 下正常安装

报错日志
Conflicting peer dependency: vue@3.4.29
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.2
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.7.1" from @vue-office/docx@1.6.2
npm ERR!     node_modules/@vue-office/docx
npm ERR!       @vue-office/docx@"^1.6.0" from the root project
npm ERR!     peerOptional @vue/composition-api@"^1.0.0-rc.1" from vue-demi@0.14.8
npm ERR!     node_modules/vue-demi
npm ERR!       peer vue-demi@"^0.14.6" from @vue-office/docx@1.6.2
npm ERR!       node_modules/@vue-office/docx
npm ERR!         @vue-office/docx@"^1.6.0" from the root project

**Comment by 501351981** [comment]
换纯js预览吧
