### ISSUE TITLE
插入附件的excel不能预览

### ISSUE THREAD

**Issue by ZERO-WL** [501351981/vue-office#305]
组件名称及版本： 如@vue-office/excel@1.7.8
运行环境：
浏览器：谷歌浏览器
vue版本：vue@3.2.40
打包工具及版本：vite@3.2.5
问题描述：插入附件的excel不能预览

**Comment by ZERO-WL** [comment]
[测试附件.xlsx](https://github.com/user-attachments/files/15895180/default.xlsx)有的可以有的不可以，这个文件不可以

**Comment by 501351981** [comment]
这个就不是xlsx文件，是xls的吧，设置 :options="{xls: true}"
