### ISSUE TITLE
@vue-office/pdf  ^0.2.5  vue3.2.1 chrome:84.0.4147.135 报错

### ISSUE THREAD

**Issue by JellNave** [501351981/vue-office#31]
pdf预览报错
pdf.js使用 ||= 浏览器版本不支持

**Comment by JellNave** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/71217359/231695336-2217070e-827c-4e0a-a474-dfc1dd841299.png">

**Comment by JellNave** [comment]
globalworkeroptions 无法正确索引 ，index.html手动导入报错依然存在

**Comment by 501351981** [comment]
仅支持 Chrome 88+，老版本不支持

**Comment by 501351981** [comment]
不支持84版本，问题关闭
