### ISSUE TITLE
网站的安全策略导致组件无法正常使用

### ISSUE THREAD

**Issue by xlf826796931** [501351981/vue-office#311]
因为我们的项目在网页的头部标签添加了Content-Security-Policy (CSP) meta 标签 ```<meta http-equiv="Content-Security-Policy" content="default-src 'self'; child-src 'none';" />```，导致了组件在生产环境无法正常预览pdf。pdf预览组件会在初始化时加载以下一段Javascript脚本。因为前面的安全策略，导致预览组件初始化失败。
[request.txt](https://github.com/user-attachments/files/16027773/request.txt)

所以如何解决这个问题

**Comment by 501351981** [comment]
改用pdfjs吧
