### ISSUE TITLE
docx文档预览时，若引用的文档中图片为svg格式，无法预览

### ISSUE THREAD

**Issue by jaweyhuang** [501351981/vue-office#312]
组件名称及版本： @vue-office/docx@1.6.2
运行环境：
浏览器：谷歌浏览器
vue版本：vue@3.2.25
打包工具及版本：vite@4.5.3
问题描述：
       docx文档预览时，若引用的文档中图片为svg格式，无法预览，
       此时图片地址就会变成blob:http://xxx 此图片必为不存在 就无法正确显示预览来。
麻烦看看，能否修复

**Comment by 501351981** [comment]
word问题依赖docx-preview，我处理不了
