### ISSUE TITLE
@js-preview/excel@1.7.11 npm包缺少libs文件夹

### ISSUE THREAD

**Issue by tengge1** [501351981/vue-office#322]
组件名称及版本：@js-preview/excel@1.7.11
运行环境：
浏览器：谷歌浏览器
vue版本：vue@2.7.14
打包工具及版本：vite@4.3.9
问题描述：npm包里少了libs文件夹。
![image](https://github.com/user-attachments/assets/44fce5eb-dac2-4d9d-94e8-e9d5bdc0e1c4)

**Comment by 501351981** [comment]
已修复 1.7.12
