### ISSUE TITLE
vu3+node16打包报错提示 Failed to resolve entry for package "@vue-office/docx". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by gene-xhh** [501351981/vue-office#328]
线上代码打包报错：
 Failed to resolve entry for package "@vue-office/docx". The package may have incorrect main/module/exports specified in its package.json.
使用场景：
组件以及依赖所在的仓库A是vue3+node16版本，安装使用cnpm
在B仓库中引用A仓库中的组件，B仓库打包过程报错
疑问：
为何工具库那么多问题，还敢发布上npm,是怎么敢的？？能理解产品是一个迭代的过程，但请不要让使用者帮你试错！

**Comment by gene-xhh** [comment]
写的什么垃圾插件，还直接关is,小气鬼

**Comment by BoomPowerful** [comment]
so?
