### ISSUE TITLE
请问目前是不支持附件的预览吗？

### ISSUE THREAD

**Issue by SebastianOvO** [501351981/vue-office#330]

**Comment by 501351981** [comment]
支持

**Comment by SebastianOvO** [comment]
但是这个文件
[testAttach.docx](https://github.com/user-attachments/files/16420572/testAttach.docx)
是包含附件的，上传到官方demo之后附件没有出现在预览页面，想问下这是正常的吗？

**Comment by 501351981** [comment]
文件里面的附件？不支持这个
