### ISSUE TITLE
excel宽高自适应没有触发

### ISSUE THREAD

**Issue by gaoyouAwait** [501351981/vue-office#336]
1，组件名称："@vue-office/excel": "^1.7.11",
2，运行环境：
 浏览器：tauri-app/"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0"
 vue版本：3.4.35
 打包工具及版本："vite": "^5.3.5"
3，问题描述：使用naiveui构建的admin系统，左边菜单，右边展示excel，左边菜单收起的时候，右边excel没有自适应宽度，右侧会显示空白，调整一下浏览器窗口，就会自适应宽度了，想知道有没有提供api来手动触发这个功能呢
![PixPin_2024-08-05_09-42-44](https://github.com/user-attachments/assets/2a5fa7f8-605e-4409-b41e-ec2260488f22)

**Comment by gaoyouAwait** [comment]
![PixPin_2024-08-05_09-58-10](https://github.com/user-attachments/assets/0ec580ed-40ec-4565-a5ff-cd200a2d2980)

**Comment by weizhigang55** [comment]
这个就是初次渲染的定死的宽高  应该没自适应，你重新渲染下就好了

**Comment by gaoyouAwait** [comment]
> 这个就是初次渲染的定死的宽高 应该没自适应，你重新渲染下就好了

问题就是怎么重新渲染，找不到对应的api

**Comment by 501351981** [comment]
弹窗或者抽屉里面，延迟一下加载组件

**Comment by gaoyouAwait** [comment]
> 弹窗或者抽屉里面，延迟一下加载组件

给父盒子加了v-if，setTimeout设置3秒才渲染，然而并没有什么用，父盒子是用flex布局的，左侧固定宽度，右侧自适应，自适应的过程没有触发组件的自适应功能

**Comment by Makabaka-goodnight** [comment]
请问您解决了吗，我也遇到了同样的问题，这个好像只是监听了body或者html元素的大小变化重新渲染宽高

**Comment by gaoyouAwait** [comment]
解决了，调整宽高之后，主动触发window的resize事件即可自适应

**Comment by 2689380792** [comment]
> 解决了，调整宽高之后，主动触发window的resize事件即可自适应

    renderedHandler() {
      this.rendered = true
      console.log("渲染完成")
      // 解决宽高bug
      this.$nextTick(() => {
        const resizeEvent = new Event('resize');
        window.dispatchEvent(resizeEvent);
      })
    },
