### ISSUE TITLE
怎么支持 后端返回的数据流

### ISSUE THREAD

**Issue by qbmiller** [501351981/vue-office#345]
1. 后端直接new File()是没问题的。
2. 但直接读取   InputStream inputStream = ResourceUtil.getStream("excelTemplate/" + name +".xlsx"); jar包下面的 文件，就不行

读出来的inputstream转成FileInputStream也不行。

从前端后 后者比直接new File（）大了很多字节

**Comment by 501351981** [comment]
后端返回数据流应该是一个通用的操作，看看别人怎么做的，类似静态服务器

**Comment by qbmiller** [comment]
> 后端返回数据流应该是一个通用的操作，看看别人怎么做的，类似静态服务器

谢谢，弄好了。java 后端 打包压缩问题；

`
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven-resources-plugin.version}</version>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>xlsx</nonFilteredFileExtension>
                        <nonFilteredFileExtension>xls</nonFilteredFileExtension>
                        <nonFilteredFileExtension>zip</nonFilteredFileExtension>
                        <nonFilteredFileExtension>pdf</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>
`
