### ISSUE TITLE
vue2引入时报错Ar.defineComponent is not a function

### ISSUE THREAD

**Issue by YUST2020** [501351981/vue-office#37]
主要依赖版本如下
├── @vue-office/excel@1.0.0
├── @vue-office/pdf@1.0.0
├── @vue/cli-plugin-babel@4.3.1
├── @vue/cli-service@4.3.1
├── @vue/composition-api@1.7.1
├── element-ui@2.15.13
├── less-loader@5.0.0
├── less@4.1.3
├── vue-demi@0.13.11
├── vue-router@4.1.6
├── vue-template-compiler@2.7.14
├── vue@2.7.14
├── vuex@4.1.0
使用import VueOfficeExcel from '@vue-office/excel'引入时报错Ar.defineComponent is not a function

**Comment by 501351981** [comment]
我用vue-cli创建了一个类似项目，没有问题，可以重新装包 vue-demi 试试，如果还有问题，可以把简化的有问题的项目发我微信 \_hit757_
