### ISSUE TITLE
Word/Excel/Pdf的打印

### ISSUE THREAD

**Issue by caobaojin** [501351981/vue-office#38]
如题，如何实现word、excel、pdf等文件的打印？

**Comment by 501351981** [comment]
可以自行通过调用window.print()，借用浏览器自带的打印功能。
如果预览页面不是单独的路由，调用window.print()可能打印含义不需要的信息，可以通过iframe嵌入一个独立的页面进行预览，然后调用iframe中的contentWindow的print方法。
