### ISSUE TITLE
ios 引用报错

### ISSUE THREAD

**Issue by shiqudemeili-new** [501351981/vue-office#39]
组件名称: "@vue-office/pdf": "^0.2.4",
浏览器: ios
vue版本: vue@2.6.14
打包工具: @vue/cli@5.0.8
问题描述
在 iphoneXr 上报错
syntaxError: Invalid character: '/#/'
data:text/javascript;base64,......................往后省略

undefined is not an object(evaluating 'window.pdfjsLib.GlobalWorkerOptions')
两个错误 pdf不能正常显示

package.json 内容
"dependencies": {
"@vue-office/pdf": "^0.2.4",
"@vue/composition-api": "^1.7.1",
"axios": "1.2.1",
"compression-webpack-plugin": "^10.0.0",
"core-js": "^3.8.3",
"docx-preview": "^0.1.4",
"echarts": "^5.4.1",
"jszip": "^3.10.1",
"lib-flexible": "^0.3.2",
"vant": "^2.12.53",
"vconsole": "^3.3.4",
"vue": "^2.6.14",
"vue-demi": "^0.13.11",
"vue-draggable-resizable": "^2.3.0",
"vue-router": "^3.5.1",
"vuex": "^3.6.2",
"vuex-persistedstate": "^4.1.0"
},
"devDependencies": {
"@babel/cli": "^7.21.0",
"@babel/core": "^7.21.0",
"@babel/plugin-proposal-optional-chaining": "^7.21.0",
"@babel/plugin-syntax-top-level-await": "^7.14.5",
"@typescript-eslint/eslint-plugin": "^5.4.0",
"@typescript-eslint/parser": "^5.4.0",
"@vue/cli-plugin-babel": "~5.0.0",
"@vue/cli-plugin-eslint": "~5.0.0",
"@vue/cli-plugin-router": "~5.0.0",
"@vue/cli-plugin-typescript": "~5.0.0",
"@vue/cli-plugin-vuex": "~5.0.0",
"@vue/cli-service": "~5.0.0",
"@vue/eslint-config-typescript": "^9.1.0",
"eslint": "^7.32.0",
"eslint-config-prettier": "^8.3.0",
"eslint-plugin-prettier": "^4.0.0",
"eslint-plugin-simple-import-sort": "^10.0.0",
"eslint-plugin-vue": "^8.0.3",
"less": "^4.1.3",
"less-loader": "^7.3.0",
"lint-staged": "^11.1.2",
"prettier": "^2.4.1",
"px2rem-loader": "^0.1.9",
"typescript": "~4.5.5",
"vue-template-compiler": "^2.6.14"
},

**Comment by shiqudemeili-new** [comment]
测试发现 在 谷歌浏览器 75版本 就会有报错

**Comment by 501351981** [comment]
是的，必须高于此版本，低版本不支持
