### ISSUE TITLE
使用 @vue-office/excel 时，xls 文件可以正常展示，xlsx 类型的文件显示为空

### ISSUE THREAD

**Issue by zgyandy** [501351981/vue-office#392]
你好，我在使用 @vue-office/excel 预览 excel 时，xls 文件可以正常展示，xlsx 类型的文件显示为空，在 https://501351981.github.io/vue-office/examples/dist/#/excel 页上传本地文件也是相同的情况。
开发环境：node18 vite5 vue3 chrome131 
有警告错误： Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
后端说导出 excel 文件用的是 easypoi。

**Comment by smmzyl** [comment]
纯前端渲染的 与后端服务无关
