### ISSUE TITLE
更新1.6.3版本后项目启动报错，Could not resolve "core-js/modules/es.symbol.js"

### ISSUE THREAD

**Issue by buludashi** [501351981/vue-office#412]
![%7B8577D058-A6B0-4016-A89A-38F7DCF16D0A%7D](https://github.com/user-attachments/assets/32840b91-6440-4770-ae41-3b914325a966)

**Comment by buludashi** [comment]
请问这意思是 新的版本，我们在项目中需要安装core-js依赖吗？

**Comment by 501351981** [comment]
安装下吧，已发布新版本，自动安装依赖
