### ISSUE TITLE
vite+ts 打包报错

### ISSUE THREAD

**Issue by hang-bro** [501351981/vue-office#42]
组件名称及版本： 
![image](https://github.com/501351981/vue-office/assets/75572675/6d1ec7c2-1164-42cd-81f0-a06f94e1a80b)

运行环境：vscode

vue版本：如vue3.2 .47
打包工具及版本：如vite@4.3.2
问题描述：
![image](https://github.com/501351981/vue-office/assets/75572675/b0f637be-4301-4079-9582-29276f710c6c)

![image](https://github.com/501351981/vue-office/assets/75572675/b53dd625-44e3-48dc-8470-b3a5438c86e0)

可以解决打包报错   将 "build": "vue-tsc && vite build" 改成 "build": "vite build"
ts打包报错希望解决

**Comment by 501351981** [comment]
下载最新版本 1.1.3 试试
