### ISSUE TITLE
vue3编译报错

### ISSUE THREAD

**Issue by Mysoli** [501351981/vue-office#44]
![image](https://github.com/501351981/vue-office/assets/41373007/154f8343-8f2c-4fa9-bd1d-913d456e10ff)
<img width="329" alt="image" src="https://github.com/501351981/vue-office/assets/41373007/84eef14a-1242-411b-9582-27588df91000">

vue3编译时报这个错

**Comment by Mysoli** [comment]
谷歌浏览器
vite 3.2.6

**Comment by 501351981** [comment]
无法复现，你可以用vite创建个项目看看，应该没有问题的，如果需要我帮忙查看，可以把简化后项目发我微信 \_hit757_
