### ISSUE TITLE
TypeError: ue.defineComponent is not a function

### ISSUE THREAD

**Issue by mlongv** [501351981/vue-office#52]
组件名称及版本： @vue-office/docx@0.1.2
运行环境：mac
浏览器：谷歌浏览器
vue版本：如vue@2.6.11
打包工具及版本：vue-cli
![image](https://github.com/501351981/vue-office/assets/25856910/c6e4556c-e5fc-40e4-9a1d-c8fffa92e31e)

**Comment by 501351981** [comment]
可能webpack版本太低了吧

**Comment by 501351981** [comment]
npm包vue版本和 引入的静态文件vue版本不一致
