### ISSUE TITLE
期望将fetch修改为xhr

### ISSUE THREAD

**Issue by lbw1998** [501351981/vue-office#53]
fetch方法可能会受到其他依赖的改写，比如在无界项目中使用fetch会被影响，期望替换xhr为fetch

**Comment by lbw1998** [comment]
我使用xhr替换了fetch，代码在这里https://github.com/501351981/vue-office/pull/54

**Comment by 501351981** [comment]
好的，其实感觉这个解决方案也有问题，无论是fetch和xhr，都可以被项目改写。
暂时合并你提交的代码，感谢参与， @vue-office/excel@1.1.6
