### ISSUE TITLE
excel组件内部滚动会影响外部滚动条

### ISSUE THREAD

**Issue by lbw1998** [501351981/vue-office#55]
1. 组件名称及版本： @vue-office/excel@1.1.6
2. 运行环境：浏览器chrome版本 113.0.5672.127（正式版本） （64 位）
3. 问题描述：在excel表格中通过滚轮键向下滚动滚动条1会影响滚动条2，在滚动条1滚动时，会影响滚动条2重复滚动
![image](https://github.com/501351981/vue-office/assets/59548278/6f198fb0-dc10-49bb-814b-b353831f6ea8)
在示例中也能复现：https://501351981.github.io/vue-office/examples/dist/#/excel

**Comment by lbw1998** [comment]
貌似不是css影响的，我修改css还是无效，但是给vue-office-excel-main添加
```
addEventListener('wheel', function(e) {
    e.stopPropagation();
});
```
也不生效，这个滚动条貌似是单独的

**Comment by 501351981** [comment]
浏览器DOM的滚动条是否出现，应该之和CSS相关，是不是外层设置为overflow:hidden即可，或者高度那里设置有问题

**Comment by lbw1998** [comment]
![image](https://github.com/501351981/vue-office/assets/59548278/7d9b5c43-a853-4434-be00-5b18455caaba)
这个滚动条是单独的，宽度只有这么一点，我只在绿色范围内滚动是正常的，如果我将滚动条宽度改成100%
![image](https://github.com/501351981/vue-office/assets/59548278/a75c5060-2ef5-47ae-a311-28d3b776c67e)
似乎就好了，这样在整个蓝色区域内作用的就是内部滚动条，但是会挡住canvas，导致不能操作表格。
感觉如果由canvas撑起整个滚动条宽度就好了。

**Comment by lbw1998** [comment]
但是x-spreadsheet-scrollbar似乎是专门单独生成的？对这块不是很清除
