### ISSUE TITLE
为啥一引入包提示我 ue.defineComponent is not a function

### ISSUE THREAD

**Issue by HongHomeDong** [501351981/vue-office#56]
![image](https://github.com/501351981/vue-office/assets/33336056/cce78e1c-ed98-4ee2-83e1-777d7c1ba76a)

**Comment by 501351981** [comment]
检查下npm里面的vue版本，和你html中引入的vue版本一致吗，就这一个截图，无法判断原因

**Comment by jackzhujie** [comment]
同样的问题
