### ISSUE TITLE
使用的vue2引用的这个包 然后打包的时候报错了

### ISSUE THREAD

**Issue by ysh98** [501351981/vue-office#57]
![image](https://github.com/501351981/vue-office/assets/26917170/bee3a943-f581-467b-bbc4-1ff763ccb685)
Octal escape sequences are not allowed in template strings

**Comment by ysh98** [comment]
开发环境使用正常 不会报错

**Comment by ysh98** [comment]
组件名称及版本： @vue-office/docx@1.1.6
运行环境：
浏览器：谷歌浏览器
vue版本：vue@2.6.10
打包工具及版本：如webpack@4.4.0

**Comment by 501351981** [comment]
没有遇到过，可以把项目demo发我微信看看 \_hit757_

**Comment by wally-lyy** [comment]
这个是什么原因呢，我也遇到了
