### ISSUE TITLE
动态src，requestOptions里的headers丢失

### ISSUE THREAD

**Issue by 18356555003** [501351981/vue-office#59]
页面静态加载没有问题
如果通过操作，动态添加src，headers会丢失

**Comment by 501351981** [comment]
https://github.com/501351981/vue-office/issues/11  请提供详细信息，不然我也无法判断

**Comment by 501351981** [comment]
试试版本  @vue-office/excel@1.1.7

**Comment by 18356555003** [comment]
> 试试版本 @vue-office/excel@1.1.7

大佬666，测试没问题了
