### ISSUE TITLE
excel预览中，时间格式显示错误

### ISSUE THREAD

**Issue by xby020** [501351981/vue-office#61]
# 运行环境
```
"@vue-office/excel": "^1.1.6"

offce软件：office 365

文件格式： .xlsx
```

# 问题描述
在excel中，如果输入时间，比如`16:00`会被格式化成`16:00:00`,如：

![image](https://github.com/501351981/vue-office/assets/26197465/4648bdd7-2195-439f-943c-7c5d48f33d26)

但是在vue-office中会被序列化成错误的格式，像这样：
![image](https://github.com/501351981/vue-office/assets/26197465/3ab4e7fc-2d85-4f5e-8f41-f7f1ac07001c)

希望能按照office 文件中的样式进行 日期/时间 格式的序列化和显示。

**Comment by 501351981** [comment]
这个从excel里面读取到 的数据就是这样的，没办法处理，建议把单元格设为字符串格式。
