### ISSUE TITLE
组件封装后在vue2.6.11版本项目中报错

### ISSUE THREAD

**Issue by GoodLuckSim** [501351981/vue-office#62]
组件名称及版本： @vue-office 全部集成
运行环境：
浏览器：谷歌浏览器
vue版本：vue@2.6.11
打包工具及版本：vue-cli 3
问题描述： 在基础组件库中封装了一个文件预览的功能组件，组件库中使用demo可以正常预览。但是组件库打包后在具体的项目中使用就会报错
![image](https://github.com/501351981/vue-office/assets/9456714/4cbfc879-887b-4fc1-8b7d-edc5edbba4ed)
组件库的package.json
<img width="400" alt="image" src="https://github.com/501351981/vue-office/assets/9456714/09ce3c08-467c-4a20-882a-2b1e4bcc9ce3">

**Comment by 501351981** [comment]
组件库打包的时候是否将 'vue-demi','vue' 排除打包呢？

**Comment by GoodLuckSim** [comment]
没有排除

**Comment by 501351981** [comment]
先试试不用vue-office可以吗

**Comment by 501351981** [comment]
用这种方式吧，更简单
