### ISSUE TITLE
doc无法预览(这个问题不大)，docx出现图表无法显示的问题

### ISSUE THREAD

**Issue by BaobeierB** [501351981/vue-office#67]
组件名称及版本： 如"@vue-office/docx": "^1.1.3",
运行环境：
浏览器：谷歌浏览器/Edge
vue版本："vue": "2.6.10",
打包工具及版本：vue-cli
问题描述：就是word自带的图表工具的图表显示不了。
![image](https://github.com/501351981/vue-office/assets/102727505/1ae6f2e5-e516-4508-a475-308a258e0cb2)

**Comment by aimer-123** [comment]
我也遇到了相同的问题，请问你解决了吗？

**Comment by zzalyp** [comment]
我也遇到了相同的问题，请问你解决了吗？
