### ISSUE TITLE
office是否加密判断

### ISSUE THREAD

**Issue by 1752146907** [501351981/vue-office#70]
大佬有直接判断word、ppt、pdf、excel是否加密的方法吗？

**Comment by 501351981** [comment]
可以试试通过jzip读取这个文件，看看能不能根据获取的信息判断是否加密

**Comment by zurmokeeper** [comment]
@501351981 可以看下 https://github.com/zurmokeeper/officecrypto-tool 这个项目，里面有

const isEncrypted = officeCrypto.isEncrypted(input);

可以用来判断docx,pptx,xlsx,xls 文件是否加密。
