### ISSUE TITLE
预览 Docx文档 时候，右边宽度不

### ISSUE THREAD

**Issue by zzdboy** [501351981/vue-office#76]
![1688544565043](https://github.com/501351981/vue-office/assets/3378222/d6ca0537-67c3-4d02-badb-0afd9a51f61b)

**Comment by zzdboy** [comment]
@501351981 这个问题如何解决

**Comment by xuyf1001** [comment]
我也差不多，这个组件预览docx文字居中显示，可以通过某个属性修改样式吗

**Comment by 501351981** [comment]
依赖docx-previewer组件，暂时无法解决
