### ISSUE TITLE
[Vue warn]: onMounted is called when there is no active component 

### ISSUE THREAD

**Issue by PhoneixT** [501351981/vue-office#77]
![image](https://github.com/501351981/vue-office/assets/46696725/439a4209-2378-4e0f-acfb-6d9e03eec1f6)
![image](https://github.com/501351981/vue-office/assets/46696725/47fb5187-3a0d-43b7-9826-d59c805b0e2f)
![image](https://github.com/501351981/vue-office/assets/46696725/c23d4f87-0736-4703-b5f8-ef33dc9546b0)

**Comment by 501351981** [comment]
用这个方案吧： https://501351981.github.io/vue-office/examples/docs/guide/js-preview.html
