### ISSUE TITLE
iOS浏览器saffer打开报错

### ISSUE THREAD

**Issue by 780291208** [501351981/vue-office#78]
Uncaught runtime errors:
ERROR
Invalid character: '#"
ERROR
undefined is not an obiect (evaluating
'window.pdfjsLib. GlobalWorkerOptions')
promiseReactionJob@ [native code]

**Comment by 501351981** [comment]
兼容性有问题，需要chrome 80以上浏览器

**Comment by 780291208** [comment]
这个能做一个提示吗？用于手机端预览pdf合同使用，目前安卓手机能够使用，在IOS端查看时会报这个错误

**Comment by 780291208** [comment]
> 



> 兼容性有问题，需要chrome 80以上浏览器

这个能做一个提示吗？
