### ISSUE TITLE
请问ppt的话可以支持吗

### ISSUE THREAD

**Issue by weizhigang55** [501351981/vue-office#79]
请问ppt的话可以支持吗

**Comment by 501351981** [comment]
ppt暂时不支持，没有好的解决方案，自己实现太费时

**Comment by weizhigang55** [comment]
谢谢回复 ppt实现起来确实很麻烦，在网上找了好多方案都很麻烦，要么收费要么不能用，对于下载型的网址链接实现方案好像不太多

**Comment by yjq-717** [comment]
https://github.com/meshesha/PPTXjs
这个ppt预览插件可以试试

**Comment by 501351981** [comment]
已支持
