### ISSUE TITLE
组件报错The setup binding property "download" is already declared

### ISSUE THREAD

**Issue by chenyu990226** [501351981/vue-office#83]
组件报错The setup binding property "download" is already declared

**Comment by 501351981** [comment]
哪个组件，什么版本呢？

**Comment by Jokevil** [comment]
我也报这个错，但是能正常显示
    "@vue-office/docx": "^1.2.0",
    "@vue-office/excel": "^1.2.0",
    "@vue-office/pdf": "^1.2.0",
    "@vue/composition-api": "^1.7.1",

**Comment by chenyu990226** [comment]
> 哪个组件，什么版本呢？

docx组件，版本应该都是最新的

**Comment by chenyu990226** [comment]
> 我也报这个错，但是能正常显示 "@vue-office/docx": "^1.2.0", "@vue-office/excel": "^1.2.0", "@vue-office/pdf": "^1.2.0", "@vue/composition-api": "^1.7.1",

我的是显示不了，后面换了其他的库完成的需求，

**Comment by 501351981** [comment]
我没有复现，试了vue2和3， vue-cli 和 vite创建的项目模板，不知道你们用的webpack几

**Comment by chenyu990226** [comment]
> 我没有复现，试了vue2和3， vue-cli 和 vite创建的项目模板，不知道你们用的webpack几

是
    "compression-webpack-plugin": "5.0.2",这个么

**Comment by 501351981** [comment]
不是 ，我是用vue-cli / vite 创建的vue2/3 项目进行测试的

**Comment by 501351981** [comment]
没关系，我用这个版本也可以，估计还是打包问题，webpack及其相关插件配置吧

**Comment by chenyu990226** [comment]
> 没关系，我用这个版本也可以，估计还是打包问题，webpack及其相关插件配置吧

好的，感谢大佬解答
