### ISSUE TITLE
xlsx 文件类型预览出现 字节丢失(表格内容不显示)

### ISSUE THREAD

**Issue by HouhaiJ** [501351981/vue-office#90]
组件及版本：@vue-office/excel：1.2.2
运行环境：谷歌浏览器 114.0.5735.134
vue版本：2.6.10
![image](https://github.com/501351981/vue-office/assets/91174822/b475b0ca-0d43-4878-93b7-836b77ab7f09)
预览excel文件出现上述警告 内容丢失的情况

**Comment by 501351981** [comment]
加我微信把文件发我看看吧， \_hit757_

**Comment by 501351981** [comment]
mockjs问题
