### ISSUE TITLE
Excel单元格内容换行无法正常显示

### ISSUE THREAD

**Issue by wwz254390130** [501351981/vue-office#91]
![image](https://github.com/501351981/vue-office/assets/45712895/8b88726a-f6ba-4a6a-8e21-40c6ffa6b596)
这个样内容高怎么怎么设置自定撑开高度

**Comment by 501351981** [comment]
被预览的文件可以设置宽点吗，估计字体多少有点不一致导致的吧

**Comment by wwz254390130** [comment]
被导出的表格设置了 单元格内换行,因为换行显示异常,要怎么处理的
alignment:{wrapText:1 自动换行}

**Comment by 501351981** [comment]
可以在默认的基础上增加宽度高度偏移量，具体见options属性配置 ，    http://localhost:5173/vue-office/examples/docs/config/#options  
<img width="804" alt="image" src="https://github.com/501351981/vue-office/assets/14229082/20fc0dca-1856-4d51-af49-cc26391f77ce">

**Comment by wwz254390130** [comment]
options配置了不生效, widthOffset和heightOffset功能并没有实现

**Comment by 501351981** [comment]
下载最新版本了吗？如果下载了，截图看看代码

**Comment by wwz254390130** [comment]
文件地址 http://media.imas.vpclub.cn/group1/M00/01/F9/eSXWjWTS8M2AJ9kXAABpDka1I9o86.xlsx
使用的版本 "@vue-office/excel": "^1.2.2"
![image](https://github.com/501351981/vue-office/assets/45712895/d3d43af3-31cd-488c-b682-2cb83e6b3a34)
