### ISSUE TITLE
使用vue-office/pdf时，页面空白，报找不到“getContext”

### ISSUE THREAD

**Issue by LR-alt** [501351981/vue-office#93]
TypeError: Cannot read properties of undefined (reading 'getContext')     at index.js:1:4277831

**Comment by 501351981** [comment]
浏览器版本多少

**Comment by LR-alt** [comment]
edge 114，这个看起来不说浏览器的问题，在个人项目是ok的，但是在公司项目使用的时候就出现这个问题。有点懵

**Comment by LR-alt** [comment]
word、excel在个人项目和公司项目上都表现正常，只有pdf有出现这个报错，想知道这个报错大概是什么原因导致的

**Comment by 501351981** [comment]
换谷歌新版浏览器看看，确定是不是兼容性问题，支持谷歌80及以上

**Comment by LR-alt** [comment]
刚才试了下，不是浏览器兼容性问题，谷歌和edge上表现是一致的

**Comment by 501351981** [comment]
不清楚，试试预览的pdf，在我提供的demo中是否能正常预览吧

**Comment by LR-alt** [comment]
我在个人项目上预览pdf是正常的，看了安装的版本是一致的，
![image](https://github.com/501351981/vue-office/assets/55624684/48f22f71-fec7-4e39-9001-6b9c07cb4b2e)

**Comment by LR-alt** [comment]
但是在公司项目上使用是不行的，所以看你的demo是否正常，意义不大
