### ISSUE TITLE
Cannot read properties of null (reading 'loadData')或Cannot read properties of undefined (reading 'GlobalWorkerOptions')

### ISSUE THREAD

**Issue by AburronKing** [501351981/vue-office#97]
1.环境 vue2.7.14 webpack v5
2. "@vue-office/excel": "^1.2.5"     "@vue-office/pdf": "^1.2.0"
3.报错：
Cannot read properties of null (reading 'loadData')
TypeError: Cannot read properties of null (reading 'loadData')
    at eval (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:57879:24)

Cannot read properties of undefined (reading 'GlobalWorkerOptions')

注：偶发性报错，pdf和excel文件多预览几次  就会出现

**Comment by 501351981** [comment]
下载最新版本试试

**Comment by hlovingness** [comment]
我也出现
