### ISSUE TITLE
 提示找不到组件

### ISSUE THREAD

**Issue by kennponn** [501351981/vue-office#98]
Unknown custom element: <vue-office-excel> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by 501351981** [comment]
展示下代码吧，这描述太简单了

**Comment by kennponn** [comment]
//引入相关样式
import '@vue-office/excel/lib/index.css'
  components: {
        VueOfficeExcel:()=>import ('@vue-office/excel')
    },

 <vue-office-excel
        :src="docx"
        style="height: 100vh;"
        @rendered="renderedHandler"
        @error="errorHandler"
    />

按照 api复制的

**Comment by 501351981** [comment]
你这是异步引入组件导致的吧，和组件本身没有关系吧
