### ISSUE TITLE
Cannot read properties of null (reading 'loadData')

### ISSUE THREAD

**Issue by isolatedchai** [501351981/vue-office#99]
你好，在使用插件后，页面上切换展现不同的附件，如果速度过于快的切换，会产生如下的报错提示

```
 Cannot read properties of null (reading 'loadData')
 TypeError: Cannot read properties of null (reading 'loadData')
     at eval (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:99:26489)
```

**Comment by isolatedchai** [comment]
组件名称及版本： 
    "@vue-office/docx": "1.2.0",
    "@vue-office/excel": "1.2.2",
    "@vue-office/pdf": "1.2.0",
运行环境：
浏览器：谷歌浏览器
vue版本：vue@2.6.14

**Comment by 501351981** [comment]
更新版本试试

**Comment by 501351981** [comment]
npm i @vue-office/excel@latest

**Comment by isolatedchai** [comment]
你好，更新到最新版本后，上面的报错不会出现而是以控制台警告的形式展现，不过不会影响到操作了，谢谢🙏
   "@vue-office/docx": "^1.2.3",
    "@vue-office/excel": "^1.2.7",
    "@vue-office/pdf": "^1.2.6"
